### ISSUE TITLE
Mark not implementing markdown extended syntax tables

### ISSUE THREAD

**Issue by AbianG** [kovetskiy/mark#100]
**Expected:** when a page with markdown includes a table (as defined on [markdown's syntax ](https://www.markdownguide.org/extended-syntax/#tables) or [Confluence's own different way of implementation](https://confluence.atlassian.com/doc/confluence-wiki-markup-251003035.html) ) it should be rendered correctly as a table on Confluence after auto-publishing with mark

**What happens:** The table is not correctly rendered and its left as plaintext. 

I don't know if its a limitation on part of mark, but seeing as Confluence even acknowledge's markdown tables, I don'tk think its a limitation on their part. I'd first like to confirm if this behaviour is happening to other people in order to then see how to solve it :)

**Comment by kovetskiy** [comment]
That's probably a bug in mark itself

**Comment by nnmm79** [comment]
If it helps, I also noticed this problem in some of my files, and when I tried to locate the difference I noticed that when I use LF as line separator, tables worked, but where I user CRLF, they did not. Maybe it will help?

**Comment by AbianG** [comment]
Thank you for the help @nnmm79. Do you mean using CRLF on all the document for the tables to work? Or just on the table's definition lines? I'd like to give this a try.

**Comment by AbianG** [comment]
I went ahead and tested changing all line endings to CRLF on a file, but still the table won't render in Confluence.

I tried using both the standard:
```
|HEADER1|HEADER2|
|---|---|
|row1|row2|
```

and also Confluence's own definition:

```
||HEADER1||HEADER2||
|row1|row2|
```
and neither of them render correctly.

**Comment by nnmm79** [comment]
The other way around. Whole markdown document needs to be saved with LF as line separator and not CRLF. In LF is line separator, tables are imported into confluence correctly using markdown tables definition.

This below is partial copy paste of table that is converted into confluence table without an issue:
`
| Column Name | Description | Example |
| ----------- | ----------- | ------- |
| ID | Auto incremented identity column | 1 |
`

**Comment by AbianG** [comment]
I confirmed having the file endings as LF, and defined the table in the same exact way. Still, it fails to render in Mark. This is really confusing. Might it have something to do with permissions of my user? Or anything not really related to the code itself?

**Comment by AbianG** [comment]
This issue is still happening, any way I can help to move it forward to resolution, @kovetskiy?

**Comment by kovetskiy** [comment]
@AbianG I'm really not sure how you can help since the issue you are describing is not reproducible.

I've just created a unit test in mark that makes sure tables renders correctly, and they do. https://github.com/kovetskiy/mark/commit/3fcfcde

Then I copied your table and tested it online:
```
<!-- Space: MARK -->
<!-- Parent: Docs -->
<!-- Title: Table test -->

*testing formats*

|HEADER1|HEADER2|
|---|---|
|row1|row2|

```

And it rendered perfectly:
![image](https://user-images.githubusercontent.com/8445924/132668613-397da893-743b-4f4c-88a3-3b2381344d84.png)

**Comment by AbianG** [comment]
You are completely correct. I managed to narrow down the problem, when defining a table, you cannot have text directly over it.

This renders:
```
Text

|HEADER1|HEADER2|
|---|---|
|row1 |row2|
```
This does not:
```
Text
|HEADER1|HEADER2|
|---|---|
|row1 |row2|
```

Indeed, its not a bug on markdown's implementation but a problem with my bad mark syntax. I apologize, and thank you for your patience :)
