### ISSUE TITLE
Custom config path option does not implemented despite it listed in README

### ISSUE THREAD

**Issue by SleepWalker** [kovetskiy/mark#103]
Hello,

There is the following line in README:

> -c <file> — Specify configuration file which should be used for reading Confluence page URL and markdown file path.

but it looks like this option isn't parsed from command line.

It would be really cool to have such feature or at least remove this option from README.

**Comment by BrutalSimplicity** [comment]
I've seen this as well.

**Comment by kovetskiy** [comment]
Yeah, that's pretty much a legacy from the previous workflow of mark. There were no meta tags (like `<!-- Space: XXX -->`) and there was a file with two fields: URL of a page in confluence and a filename, and then a git hook was executing mark and specifying this file as config).

What kind of a problem did you try to solve with a config? Do you need to store your credentials somewhere else (currently they should be stored in ~/.config/mark if I'm not mistaken)?

**Comment by SleepWalker** [comment]
It's not that convenient to store creds in home dir. Normally credentials are stored in a local file, e.g. `.env` (that also has a bonus feature of specifying creds view env vars).

But in my case using docker, I've just mounted local file to the home dir of container like so:

```
docker -v `pwd`/mark.config.toml:/root/.config/mark -v `pwd`:/docs --rm -i kovetskiy/mark:latest mark ...
```

**Comment by kovetskiy** [comment]
Should be fixed in b1eea83d4950a7e73038afa38e073f8002b71485 in the version 6.2, let me know if the issue can be closed

**Comment by SleepWalker** [comment]
@kovetskiy can you please publish the latest version to docker registry? Currently there is 5.7 as the latest: https://hub.docker.com/r/kovetskiy/mark/tags?page=1&ordering=last_updated

**Comment by kovetskiy** [comment]
@SleepWalker thank you for your patience, I was in kind of vacation and then got busy with other projects. Sure thing, I've just released it on dockerhub.

**Comment by SleepWalker** [comment]
@kovetskiy thank you, it works fine. Closing an issue
