### ISSUE TITLE
dockerhub publishing?

### ISSUE THREAD

**Issue by pnancarrow** [kovetskiy/mark#108]
Hey, are you no longer publishing to dockerhub? It seems the latest release there is 5.7. https://hub.docker.com/r/kovetskiy/mark/tags?page=1&ordering=last_updated

**Comment by kovetskiy** [comment]
Hi, I do, but sometimes I forget about it, we actually need to improve the github actions pipeline to release docker images automatically too.

**Comment by pnancarrow** [comment]
Thanks for manually updating in the mean time!

**Comment by mrueg** [comment]
I believe this is resolved. Please let me know if it's not.
