### ISSUE TITLE
Cloud Confluence Support?

### ISSUE THREAD

**Issue by awagneratzendesk** [kovetskiy/mark#13]
Hello! 

I'm interested in trying this out for dynamically building some documentation for a project I'm working on that can't be easily replicated with native Confluence functionality but could be maintained with a bit of Python and elbow grease.

I've generated an API token and setup the config file like so:

```
username = "myuser"
password = "myapitoken"
base_url = "https://mycompany.atlassian.net"
```

I've gone ahead and generated a sample .md file for testing like so:

```
<!-- Space: MYSPACEKEY -->
<!-- Title: mypagetitle -->

## This is title 1

## This is title 2
```
However, I get the following errors:

```
2019-11-22 14:58:00 [FATAL] unable to resolve page
                            └─ can't create ancestry tree: 
                               ├─ can't find root page for space "MYSPACEKEY"
                               │  └─ no such space
                               │
                               └─ title: mypagetitle
```

I know that the space key exists - do you know of anything that might be causing this to fail to find the page? I'm wondering if this is a Cloud Confluence issue?

**Comment by huksley** [comment]
Hi, this is really simple
base_url should be with /wiki
i.e. `base_url = "https://mycompany.atlassian.net/wiki"`

Please, test it out, and if works, close this issue!

**Comment by awagneratzendesk** [comment]
I can confirm that works - thanks for pointer!
