### ISSUE TITLE
Allow include to traverse back up directories

### ISSUE THREAD

**Issue by antonym** [kovetskiy/mark#132]
Thanks for the great tool, I wanted to see if something like this would be possible to add. 

I'd like to have a common header like the disclaimer.md example, but I'd like multiple directories to reference the single header.  I have several directories for organizing the markdown files, but I'd like a common directory that I could traverse back up the tree to pull in the common header file without having to have a duplicate copy in each directory.

Would it be possible to do something like this so that I can put a disclaimer on every page?  Currently it does not know how to traverse back up the directory tree.

```
<!-- Include: ../common/header.md -->
```

Thanks!

**Comment by digital-synapse** [comment]
Markdown inclusions (for example including an image) are always relative to the markdown file. however mark handles inclusions (via the ```<!-- Include: ../common/header.md -->``` syntax) as relative to work directory where mark is executed.

I ran into this same issue and was able to temporarily workaround by writing a small bash script, to find all of the subfolders with markdown then in a for loop, cd to each folder before running mark on the md files in that folder.

``` bash
#!/bin/bash
root=$PWD
config="$root/.mark.config"
array=( $( find . -name "*.md" -type f -exec echo "$(cd "$(dirname "$f")" && pwd -P)/$(basename "$f")" {} + ) )

for path in "${array[@]}"; do (
  folder=$(dirname "$path")
  file=$(basename "$path")
  dir=$(dirname "${path}")
  
  # ignore anything in ./include and files called readme.md
  if [[ -f "$path" ]] && [[ "$folder" != "./include" ]] && [[ "$file" != "readme.md" ]]; then
    echo "path=$path  folder=$folder  file=$file  dir=$dir"
    cd "$dir"
    
    # use a config file if present, otherwise use env vars
    [[ -f "$config" ]] \
      && mark -c "$config" -f "$file" \
      || mark -u $CONFLUENCE_USER -p $CONFLUENCE_PASS -b $CONFLUENCE_URL -f "$file"
    cd "$root"
  fi
) done

```

**Comment by kovetskiy** [comment]
What is your usecase where you need to include a file relatively to the current file?

**Comment by antonym** [comment]
In our use case, we have documentation structured to align with the wiki structure and we have a common folder that is used to pull in headers that says all docs are maintain in git on every article:

```
docs/common/header.md
docs/section1/index.md
docs/section2/index.md
docs section3/index.md
```

I'd like to be able to use a common header file to avoid duplicate code to reference that file. Currently to get around this, I'm using a symlink in CI to link the common file to the local directory the documentation resides in. Allowing it to traverse up for the file, would simplify this.

Being able to do something like this:

```
<!-- Include: ../common/header.md -->
```
Would greatly simplify usage and reduce duplicate code.

**Comment by kovetskiy** [comment]
But why would you change current directory to a file’s directory and then
include with ../ if you could just not change the directory and include
file by a relative to the root directory path?

**Comment by digital-synapse** [comment]
@kovetskiy consider a folder structure like this
```
Space/
|
|---- Page 1/
|        |
|        |---- Page 1.md
|        |---- Sub Page 1-1.md
|        |---- Sub Page 1-2.md
|        |---- images/
|
|---- Page 2/
         |
         |---- Page 2.md
         |---- Sub Page 2-1.md
         |---- Sub Page 2-2.md
         |---- images/
```

Viewing the markdown preview expects the image path to be relative to the file but mark expects it to be relative to the working directory where mark was executed.

That means previewing a sub-page with an image included like this works fine in the markdown preview, but fails when publishing with mark.
```![Example checkov output](images/checkov-output.png)```

Assuming you were running mark from the root folder Space/ mark expects the attachment to look like this
```![Example checkov output](Page 2/images/checkov-output.png)```

In the second case, mark will publish correctly but previewing the markdown locally will fail to render the image. This would also be true if you were using a global attachments folder. the preview would expect the path relative to the markdown file but mark expects the path relative to the working directory.

So to answer your question, why my workaround changes the current directory. To make sure that local previewing and publishing both work as expected.

The same problem also affects relative paths of include files as in the OP's case, but it's easier to illustrate with image attachments.

**Comment by antonym** [comment]
Looks like this using `../path` may work now with this latest change:

https://github.com/kovetskiy/mark/commit/9a4f9ff32dd3ec9005bee177fc4be6d5f8250aee

**Comment by kovetskiy** [comment]
That's true, the issue should be resolved with the newest major release by now.
