### ISSUE TITLE
Please consider supporting homebrew package management

### ISSUE THREAD

**Issue by kquinsland** [kovetskiy/mark#135]
Thank you for creating this tool! It looks like a perfect solution to our "documentation with the code vs documentation where everybody knows how to find it" debate.

Would you consider adding support for the _excellent_ [home-brew package manager](brew.sh)?

The exact details are outline in a few different sections on the [brew docs page](https://docs.brew.sh/) but in short:

- a small ruby file (called a [`formula`](https://docs.brew.sh/Formula-Cookbook)) is added to this repo and that file points to the [binary release files hosted here on github](https://github.com/kovetskiy/mark/releases)
- a pointer to that ruby file is either included in the upstream list that is distributed by the homebrew team or can be used independently.

Once a given instance of `brew` is aware of the formula for `mark`, a user only needs to type `brew install mark` to get the latest pre-compiled binary (or, built from source) installed into $PATH.

There is a small tool meant to assist in creating formula for golang programs called `fgo`: https://jkawamoto.github.io/fgo/

**Comment by kovetskiy** [comment]
Hi! I'm a Linux user and don't really know/care much about Mac OS. I would be really glad to accept a PR with this brew's tap which probably can be copied from another project: https://github.com/reconquest/tubekit/blob/master/tubekit.rb since we don't need to use Go and we have releases to download.

**Comment by kquinsland** [comment]
@kovetskiy  No worries. I am primarily a *nix user too but for work we have a lot of mac users. There is a *nix port of `homebrew` as well.

You're correct, there is technically no need to include 'build it yourself' instructions in the formula if there is already a bre-built binary available so `fgo` could be overkill; making small changes to an existing file would be sufficient.

And as it turns out @mmiranda beat me to it with #137.

**Comment by mmiranda** [comment]
I think this issue can be closed since #137  is already merged.

I confirm mark is being installed on my computer with no issues.

```
brew tap kovetskiy/mark
brew install mark
```
