### ISSUE TITLE
HTTPS connects

### ISSUE THREAD

**Issue by t794104** [kovetskiy/mark#14]
By company uses a confluence server with a https which uses a internal CA.

How do i get 'mark' too connect too the https and work ? Other words how do i add a ca.crt ?

**Comment by kovetskiy** [comment]
Hi,

you can solve this problem on the system level by adding your self-signed certificate into the pool of trusted certificates

On Ubuntu you can do it like that: https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu

On Arch Linux you can just call `trust anchor` and pass the path to certificate: https://unix.stackexchange.com/questions/373492/installing-certificates-on-arch

**Comment by t794104** [comment]
I got it working, thanks

**Comment by gongzili456** [comment]
how to use .p12 file ?

**Comment by kovetskiy** [comment]
@gongzili456 I don't know how to use it with mark. But one thing I'd point is that mark doesn't implement any SSL communication itself, it uses the same ways as other programs, so you just need to install it into the system somehow.
