### ISSUE TITLE
iframe support for cloud version

### ISSUE THREAD

**Issue by guoweis-outreach** [kovetskiy/mark#140]
Hi,

For cloud version, https://support.atlassian.com/confluence-cloud/docs/insert-the-iframe-macro/

Are we open to add support of such? If so, I can submit a PR to enable this.

Thanks

**Comment by kovetskiy** [comment]
Hi

Sure, I'm open to merge anything that will only improve everyone's experience with the tool.

**Comment by guoweis-outreach** [comment]
tried to submit a PR but got this 

```
ERROR: Permission to kovetskiy/mark.git denied to guoweis-outreach.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kovetskiy** [comment]
Looks like you are trying to push into my repository directly, you should create a fork of my repository, push your code in your repository and then create a Pull Request from your repository into my repository.

Here is the doc: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by guoweis-outreach** [comment]
Thanks for the clarification. https://github.com/kovetskiy/mark/pull/143
