### ISSUE TITLE
Option to disable template parsing on include tag

### ISSUE THREAD

**Issue by alexander-rabenstein** [kovetskiy/mark#142]
I want to be able to include for example ansible files. Ansible uses jinja as templating engine which apparently uses the chars to mark variables "{{ variable }}". 

Therefore its currently not possible to include an ansible file with mark as mark tries to parse the file and substitute variables. 

To fix this an option could be added to the include tag to disable parsing.

**Comment by kovetskiy** [comment]
I'm not sure how to avoid this behavior, but I'd suggest escaping these {{ symbols like `{{"{{"}}`. I understand that this is kind of cumbersome tho

**Comment by alexander-rabenstein** [comment]
As the file I want to include is part of the ansible playbook I am trying to document automatically its hard to change the file. 
But what could be a possibility to add  new mark tag inside the file to include to tell the parser that this is not a template 
something like  
or more flexible to change the delimeter of the template engine 
The go template module seems to support changing the delimiter [https://pkg.go.dev/text/template#Template.Delims]

**Comment by Skeeve** [comment]
See PR #195
