### ISSUE TITLE
When pushing to confluence, all comments on the page are lost

### ISSUE THREAD

**Issue by guoweis-outreach** [kovetskiy/mark#144]
We noticed that when we push the page through `mark`, the existing comments are all wiped out. Is this a known issue?

**Comment by guoweis-outreach** [comment]
this is the dup of https://github.com/kovetskiy/mark/issues/68

**Comment by chipbite** [comment]
@guoweis-outreach - propose that you close this issue, since there is already one created (the one you found I mean).
