### ISSUE TITLE
Same Page Name Issue

### ISSUE THREAD

**Issue by AndiRudi** [kovetskiy/mark#149]
I think there is a bug with same naming and the page tree.
I have a structure to explain services

* Service1
  * introduction
  * some stuff
* Service2
  * introduction
  * something else
 
As you can see the first page for each service has the same name.

```
 FATAL unable to resolve page
└─ unexpected ancestry tree, did not find expected parent page in the tree
├─ expected parent: Service2
├─ list: Backend; Backend Services; Service1
└─ title: introduction
```
Please note how it is finding `Service1` in the list. There is no mentioning of `Service1` in the whole repository.

The config on the second service looks like this
```
<!-- Space: TECH -->
<!-- Parent: Backend -->
<!-- Parent: Backend Services -->
<!-- Parent: Service2 -->
<!-- Title: introduction -->
```

I don't understand why it's finding Service1s "introduction" instead of creating the "introduction" below Service2. It almost seems like it doesn't understand a tree structure. By the way if I rename the "introduction" to "introduction2" it works just fine.

**Comment by kovetskiy** [comment]
This is true, mark expects pages' titles to be unique. So what it does is that it finds a page called "introduction" and checks if the tree is the same as expected before updating the contents. If it is not equal to what is expected, then it gets rejected.

It's possible to avoid this behavior if you rename your page to something like `Introduction to Service2` and `Introduction to Service1`. 

The other way is to submit a PR which would improve `mark`'s behavior, I'd be glad to merge such a feature.

**Comment by AndiRudi** [comment]
Understood. It would maybe be enough to just get a list of all pages with the same name and compare all the found trees if one of them fits. I am not proficient in Go just yet...

**Comment by antonym** [comment]
For what it's worth, I'm seeing similar behavior, +1 to seeing this improved.

**Comment by anig1scur** [comment]
Actually it's not supported officially by Confluence, when you're trying to create same name page in one space

![image](https://user-images.githubusercontent.com/52899668/155955804-76a8bc02-f90c-4694-88b8-e3901310e77c.png)

**Comment by AndiRudi** [comment]
I think @anig1scur is correct so I will close this issue from my side.
