### ISSUE TITLE
Can we skip ancestry tree ?

### ISSUE THREAD

**Issue by t794104** [kovetskiy/mark#15]
We're uploading following files with the meta :
Changelog.md :
```
<!-- Space: ACS -->
<!-- Parent: Library -->
<!-- Title: Library - Changelog -->
```

Library.md : 
```
<!-- Space: ACS -->
<!-- Parent: Ansible Roles -->
<!-- Title: Library -->
```

Both will upload too confluence when they are not there already. And the library.md will update with every change. But the Changelog.md does not.

Inital upload changelog.md : 
```
#  docker run -ti -v=$PWD:/docs artifacts.kpn.org/acn_community/comm/markdown:1.0 -b https://confluence.kpn.org/ -u XXXX -p XXXX
2020-01-03 13:09:36 [TRACE] loaded macro "@\\{([^}]+)\\}"
                            ├─ template: ac:link:user
                            ├─ expr: @\{([^}]+)\}
                            └─ config: map[Name:${1}]
2020-01-03 13:09:36 [DEBUG] resolving page path: ??? > Library > Library - Changelog
2020-01-03 13:09:37 [DEBUG] parent page "Library" exists: /display/ACS/Library
2020-01-03 13:09:37  [INFO] page will be stored under path: ACN Community Software Home > Ansible Roles > Library > Library - Changelog
....
```

When updating the changelog.md : 

```
#  docker run -ti -v=$PWD:/docs artifacts.kpn.org/acn_community/comm/markdown:1.0 -b https://confluence.kpn.org/ -u XXXX -p XXXX
2020-01-03 13:10:02 [TRACE] loaded macro "@\\{([^}]+)\\}"
                            ├─ template: ac:link:user
                            ├─ expr: @\{([^}]+)\}
                            └─ config: map[Name:${1}]
2020-01-03 13:10:02 [FATAL] unable to resolve page
                            └─ broken ancestry tree; expected tree: Library > Library - Changelog; encountered "Ansible Roles" at position of "Library"
                               └─ title: Library - Changelog
```

So we can do the initial upload but no updates after. This because the ancestry can't be validated. Do we need to validated it ? Is there a real reason to check it ? Because we didn't need it when we created the page. Can it be made optional ?

**Comment by kovetskiy** [comment]
Hi, could you try branch `skip-ancestry-improve-dry-run` I have removed that check full ancestry tree and have improved dry-run mode, please make sure that you run `--dry-run` for the first time and check that the path is correct.

I did the checks on fresh docker confluence setup (v7.2.0).

**Comment by t794104** [comment]
Thanks for the fast reply, but i'm at home and can't test it right now. I'll give it a try on Monday and get back too you.

**Comment by t794104** [comment]
I tryed building a docker image and got the following error 👍

**Comment by kovetskiy** [comment]
Please try now, I've fixed the work path in Dockerfile

**Comment by t794104** [comment]
Oke, next error i get is :

```
Step 6/12 : RUN make build
 ---> Running in 540fd9d6ff72
:: building go binary 56.f52b060
CGO_ENABLED=0 go build \
        -ldflags "-X main.version=56.f52b060" \
        -gcflags "-trimpath /go/src"
Removing intermediate container 540fd9d6ff72
 ---> 91425a7b4ab0
Step 7/12 : FROM alpine:latest
 ---> 961769676411
Step 8/12 : RUN apk --no-cache add ca-certificates bash
 ---> Using cache
 ---> 120605ff2d10
Step 9/12 : COPY --from=0 /go/src/mark/mark /bin/
COPY failed: stat /var/lib/docker/overlay2/d38ac576c6a44474dd0094433229d93c2434adca81a0c001d72cc2aa1cec70b0/merged/go/src/mark/mark: no such file or directory
```
Seems it can't find the file from the previous build ?

**Comment by kovetskiy** [comment]
@t794104 please try now :pray:

**Comment by t794104** [comment]
Yep build now.

And works like we wanted/expected.
Will this get merged back into the master ?

**Comment by kovetskiy** [comment]
@t794104 Yep, just wanted your confirmation, it's in master now. Thanks!

**Comment by t794104** [comment]
Works like a charm, thanks

**Comment by GezimSejdiu** [comment]
Hi @kovetskiy , 

first of all, thanks a lot for providing such a nice tool for syncing Markdown documents with the Confluence page. Something quite useful and needed when there is a need to sync the documentation among two different platforms. Thank you.

I just gave it a try and was wondering if I'm doing something wrong when applying updates to the page.

I was able to create the page on Confluence but whenever I try to update it I get this: 

```
2021-02-01 13:40:56.150 FATAL unable to resolve page location
                              └─ page "Test Page" has fewer parents than specified: Parent1 > Parent2 > Parent3 > Parent4 > Parent5 > Parent6 > Test Page
```
and the configuration is as follow:
```
<!-- Space: TestSpace -->
<!-- Parent: Parent1 -->
<!-- Parent: Parent2 -->
<!-- Parent: Parent3 -->
<!-- Parent: Parent4 -->
<!-- Parent: Parent5 -->
<!-- Parent: Parent6 -->
<!-- Title: Test Page -->
```
and run it via :
```
mark -u $username -p $password -b $mark_url -f $file
```

I'm a bit confused why it was able to create initially but not able to update the page. I'm posting here as it may be related with the ancestry tree check, but I'm not completely sure if the issue is related. I also did check the logs by enabling `--trace` but I can't find anything useful. The page is _unversioned_.

Best regards,
Gezim

**Comment by kovetskiy** [comment]
@GezimSejdiu hey, could you try the latest version 4.2? It's not going to fix the issue, but it will show what ancestors were expected and what are the actual ones.

**Comment by GezimSejdiu** [comment]
Hi @kovetskiy , thanks a lot for your prompt reply. 

I just did try it with 4.2 (docker) and got the expected ancestors.
```
2021-02-02 08:23:19.164 FATAL unable to resolve page
                              └─ the page has fewer parents than expected
                                 ├─ title: Test Page
                                 ├─ actual: Parent1 > Parent2 > Parent3 > Parent4 > Parent5 > Parent6
                                 ├─ expected: Parent1>Parent2>Parent3>Parent4>Parent5>Parent6>Test Page // oh, here it goes one level down :( including the page itself as Parent which isn't true from the configuration.
                                 └─ title: Test Page
```

It seems that the tree is also including the page as one of the parents on the ancestor's tree :( -- which shouldn't be the case, I guess. 

Do you think I'm missing something withing the configuration or something while executing it which may help me to prevent such a scenario when updating the pages?

Once more, thanks a lot for your support.

Best regards,
Gezim
