### ISSUE TITLE
Attachments missing

### ISSUE THREAD

**Issue by malys** [kovetskiy/mark#155]
Hi,
I use mark. The upload of attachments  has worked well.
Since a couple a day, for the same MD file which worked, currently, it's not working well.
Body is uploaded in confluence but attachments were not. Moreover, mark is not generating error and using debug or trace modes, I can't detect the origin of this issue.
Could you help to understand what happens? ( Method to debug, to analyze ...)
I have tried to change relative of attachments and nothing
Thanks

**Comment by kovetskiy** [comment]
Hi, could you provide trace logs and minimal source file with sensitive information removed from it?

Also, do you use confluence cloud or confluence server (and which version if it's server)?

**Comment by malys** [comment]
Thanks for your help @kovetskiy 

https://gist.github.com/malys/fb9b7e3dbdd04720f9c9c8a8f7dfade4 contains wanted informations. If you are detecting sensitive data in gist please inform me.
If it's necessary I can share with you unformatted trace.

**Comment by kovetskiy** [comment]
I see, that's because mark is looking for triple line break after meta tags to start rendering the real content, and you have these line breaks before the `<!-- Attachment`

```markdown
<!-- Space: RHSSO -->
<!-- Parent: infrastructure -->
<!-- Title: authentication domains -->


<!-- Attachment: ./plantuml/architecture-intra.puml.png -->

<!-- Attachment: ./plantuml/architecture-inter.puml.png -->


## Test
```

Try the following instead:

```
<!-- Space: RHSSO -->
<!-- Parent: infrastructure -->
<!-- Title: authentication domains -->
<!-- Attachment: ./plantuml/architecture-intra.puml.png -->
<!-- Attachment: ./plantuml/architecture-inter.puml.png -->


## Test
```

This seems like a bug that should be fixed though, mark should tolerate such tags placements.

**Comment by malys** [comment]
Great @kovetskiy! It was tricky and It's currently working well.

FYI and it could be inspired you:
I have created a pre processing script https://gist.github.com/malys/bda40629445f12e5a3bcb90a81daab63

  => generate automatically image from release_stable.puml to attach it
 => insert code snippets

Thanks a lot.
