### ISSUE TITLE
Recent change to how attachment path is handled

### ISSUE THREAD

**Issue by markszabo** [kovetskiy/mark#157]
I have a folder structure like this:

```
mark.sh
docs/
  - manuals/
     - device1.md
     - imgs/
       - device1.png
```

mark.sh has the `mark` command and it is run from the topmost directory (e.g. n `cd` command in the script). It runs in `kovetskiy/mark:latest` docker container. 

`device1.md` uses `device1.png` as an attachment like this:

```
<!-- Attachment: ./docs/manuals/imgs/device1.png -->

![Device1](./docs/manuals/imgs/device1.png)
```

The path was given relative to the folder the `mark` command is run from, not relative to the markdown file.
This has been working fine until yesterday, when `mark` started to give the following error:

```
2022-01-20 04:19:14.085 DEBUG parent page "Manuals" exists: /display/space/Manuals
2022-01-20 04:19:14.085 INFO  page will be stored under path: Space > Manuals > Device1
2022-01-20 04:19:14.085 FATAL unable to create/update attachments
                              └─ unable to get checksum for attachment: "./docs/manuals/imgs/device1.png"
                                 └─ unable to open file
                                    └─ open docs/manuals/docs/manuals/imgs/device1.png: no such file or directory
```

If I update the path to be relative from the markdown, e.g. `./imgs/device1.png`, it works.

Was there any change recently that might have caused this? Or was the relative-to-markdown path always the correct way to specify attachments and I just got lucky that it worked like this before? I don't mind updating all my markdowns to relative paths, but I want to understand what happened and make sure I don't need to go back to the original path later.

**Comment by kovetskiy** [comment]
Hi, this has been changed with the major version bump because of 
https://github.com/kovetskiy/mark/pull/151

**Comment by markszabo** [comment]
Gotcha, thank you!
