### ISSUE TITLE
download a confluence page as markdown

### ISSUE THREAD

**Issue by dfroger** [kovetskiy/mark#159]
Hi,

I'm not sure to understand the workflow. If someone creates or modifies a page using the online Confluence Wysiwyg, can I download the page as a markdown document? (ie, download the page in storage format with the REST API, and convert it to markdown). So i can resolve the diff with my markdown page before the Wysiwyg update.

If I can't, does it mean that the Wysiwyg has to be forbidden? I can't imagine a company that would use Confluence without Wysiwyg.

My use case would be to let people use the Wysiwyg, and to allow developers to create/update the same documents with markdown (so taking into account the creation/update from the Wysiwyg). Is it possible?

Thanks!

**Comment by kovetskiy** [comment]
Hi, it's currently not possible in the way you describe. The documents are not supposed to be edited in Confluence itself.

**Comment by dfroger** [comment]
Thanks for the clarification. So the workflow is rather to publish in a read-only way a documentation written elsewhere by developers. I can close the ticket, thanks for the reply.
