### ISSUE TITLE
Unable to find page in Confluence SaaS

### ISSUE THREAD

**Issue by korysansom** [kovetskiy/mark#166]
I've used Mark for a Confluence server hosted on-prem but I'm trying to set it up for Confluence SaaS. Is this possible? What does a typical `.config/mark` look like for Confluence SaaS? Is the base url everything before `/wiki/`?

Assuming the base url and space Id is as follows:
`{base_url}/wiki/spaces/{spaceId}`
`https://instance.atlassian.net/wiki/spaces/~123456123`

```bash
2022-03-09 15:06:50 [FATAL] unable to resolve page location
                            └─ can't create ancestry tree: 
                               └─ can't find root page for space "**REDACTED**"
                                  └─ no such space
```

**Comment by kovetskiy** [comment]
Hi, the base url should not contain `/spaces/` path, you specify path with `SPACE` directive in the document itself. Try just `https://instance.atlassian.net/wiki/` instead

**Comment by korysansom** [comment]
I've added `/wiki/` to the base url and another error showed up. I'm trying to figure out my username as it doesn't appear to be my email. I've tried using the id found in my profile url but same error. Could there be another id or username?

`https://instance.atlassian.net/wiki/people/5d71708366fb`

```bash
2022-03-09 22:24:35 [FATAL] unable to resolve page location
                            └─ error while finding page "Mark Atlassian Confluence"
                               └─ Confluence API returned unexpected status: 401 (Unauthorized)
```

**Comment by kovetskiy** [comment]
You probably forgot to use your unique api key instead of password

**Comment by korysansom** [comment]
That was it. Thank you!
