### ISSUE TITLE
Set parent page(s) via CLI param

### ISSUE THREAD

**Issue by ITler** [kovetskiy/mark#168]
I would like to handle page structure in confluence via pipeline rather than defining within the markdown files themselves.
I would suggest to add a CLI option `--parent`, which could be called multiple times, like

``` bash
mark --space MySpace --parent page1 --parent "page2 with whitespaces" ... --parent pageN \
     --title-from-h1 -f my.md
# or if more suitable
mark --space MySpace --parent "page1,page2 with whitespaces,...,pageN" --title-from-h1 -f my.md
```

What do you think? Would this make sense? Would you be able to implement that functionality?

**Comment by kovetskiy** [comment]
Why would you want that? I mean we have these html tags which do the trick already, is there any specific scenario where you would like to have such a feature?

**Comment by slaughtr** [comment]
I can provide an example for why this might be helpful!

Currently, the person writing the markdown has to insert the parent pages in some format, which can be error-prone and pretty much kills the ability to use a file/folder structure in your markdown to dictate the end result in Confluence.

With the ability to pass parents via CLI command, you could do something like:

```sh
PARENTS=$(dirname "$(realpath --relative-to=. ./My Docs/My Project/Project Section/Some Path/MyPage.md)" | tr / ,)
# PARENTS becomes "My Docs,My Project,Project Section,Some Path"
mark --space MySpace --parent "$PARENTS" -f ./My Docs/My Project/Project Section/Some Path/MyPage.md
```

This would allow authors to skip the parents thinking entirely, and for those of us who are using them entirely to preserve the directory structure we'd be able to get that with a simple bit of scripting.

**Comment by ITler** [comment]
thanks for explaining my thoughts :)

**Comment by Skeeve** [comment]
wouldn't a `--parents-from-location` be useful? If I understood correctly, the Confluence structure should mimic the folder structure, correct?

**Comment by ITler** [comment]
This wouldn't be flexible enough. Maybe your file structure only reflects a subset of the confluence doc structure... So explicitly defining the parent seems to me being the simpler and more flexible approach

**Comment by Skeeve** [comment]
How about defining the parent in a configuration file per folder? `.mark_rc`

That way a responsible person can put the configuration into that file and the users need not take care.

Additionally there would be no need to enter the same stuff on the commandline every time you publish and also no need for a publish-script, which one might forget about.

**Comment by ITler** [comment]
yeah why not, if 
* the format is 'easy' means, could be assembled easily on the fly with a bash script, 
* I could define multiple parents (path notation)
* maybe mark can traverse up the file system to find that file.

```
/ project root
  L doc
     L file.md  # mark executed here, but finds .mark_rc
.mark_rc 
```

**Comment by Skeeve** [comment]
So why don't you write down your ideas for that?

I am neither a hard-core Confluence user, nor a go-guru. I just discovered `mark` last week and found it quite useful for me.

So if you can explain to me what the semantics of multiple parents is and how you think it would be useful to define them in a configuration file, I can think about implementing it. Maybe it will be useful for me too.

**Comment by Skeeve** [comment]
> I am currently thinking I'll have to run multiple mark commands to point to the correct page to modify, which is fine, but it would be better if I could run the command once and recurse the folder structure and replicate it in confluence.

So you'd like to have the same folder structure you have in your source/github be replicated in confluence?

Maybe this shell script for publishing your documentation gets you going?

```SHELL
#!/bin/bash

# Prepare a "separator"
sep="$( echo ' -->' ; echo '<!-- Parent: ')"

# Find all markdown files.
# Make sure your path doesn't start with "./"
find * -name \*.md | while read f ; do

    # get the directory path
    dir=$( dirname "$f" )

    # Replace every "/" with the separator
    # thus make the directory path be a list of all the file's parents
    parents="<!-- Parent: ${dir//\//$sep} -->"

    # Prepend the parents to the file
    {
        # Here you could also set the space etc.
        echo "$parents"
        cat "$f"
    } > "$$.md"
    # The modified file is stored in a temporary variable

    # Publish the temporary file (here: A dry-run)
    mark --dry-run -f "$$.md" 

    # delete the temporary file
    rm "$$.md"
done
```

**Comment by ayzenquwe** [comment]
That's pretty sad that the tool doesn't have this feature. :( We structure our documentation through a dir tree. Also we want to keep our docs free from any meta tags or anything related to external tools, as Confluence is not the only target application we use. Which means we have to write a script that will add meta tags for mark during CI.

**Comment by Skeeve** [comment]
> Also we want to keep our docs free from any meta tags or anything related to external tools, […] Which means we have to write a script that will add meta tags for mark during CI.
That's what my script above does. Just prepending the meta tags to the original file, putting the result into a temporary file which is afterwards deleted.

**Comment by ayzenquwe** [comment]
> That's what my script above does. Just prepending the meta tags to the original file, putting the result into a temporary file which is afterwards deleted.

Yep, this is exactly what we're doing. Your script is very helpful. :)

**Comment by viclang** [comment]
With help from @Skeeve's script and ChatGPT I created this bash script:
```bash
#!/bin/bash

process_markdown() {
    local file="$1"
    # If there is no Parent then generate_parents
    grep -qF "<!-- Parent: " "$file" || generate_parents "$file"
    # If there is no Title then generate_title
    grep -qF '<!-- Title: ' "$file" || generate_title "$file"
    printf "\n"
    transform_devops_mermaid_code_blocks "$file"
}

generate_parents() {
    local file="$1"
    local dir=$(dirname "$file" | sed 's/\.[^.]*$//; s/-/ /g')
    local sep="$( echo ' -->' ; echo '<!-- Parent: ')"
    echo "<!-- Parent: ${dir//\//$sep} -->"
}

generate_title() {
    local file="$1"
    local existing_title=$(sed -n 's/<!-- Title: \(.*\) -->/\1/p' "$file")
    local generated_title_from_filename=$(basename "$file" | sed 's/\.[^.]*$//; s/-/ /g')
    local title=${existing_title:-$generated_title_from_filename}
    echo "<!-- Title: $title -->"
}

transform_devops_mermaid_code_blocks() {
    local file="$1"
    sed -e '/^:::mermaid$/,/^:::$/ { 
            s|^:::mermaid$|```mermaid|; 
            s|^:::$|```|; 
        }' "$file"
}

# Iterate over markdown files
find * -name \*.md | while read -r file; do
    process_markdown "$file" > "$$.md"
    
    mark --debug --trace -f "$$.md"
    
    rm "$$.md"
done
```

I don't have any experience with Go, but is it possible to integrate some of the functionality?

**Comment by mrueg** [comment]
Since this is something a couple of folks want, I've added a possible solution here: https://github.com/kovetskiy/mark/pull/343 please test and give it a try.
