### ISSUE TITLE
ac:status macro not displaying text

### ISSUE THREAD

**Issue by korysansom** [kovetskiy/mark#187]
When I try creating two different ac:status macros, one for yes (green) and one for no (red), the Title is not correct.

```
<!-- Macro: :yes:
     Template: ac:status
     Title: Yes
     Color: Green -->

<!-- Macro: :no:
     Template: ac:status
     Title: No
     Color: Red -->
```

![Screen Shot 2022-05-19 at 11 56 53 AM](https://user-images.githubusercontent.com/54757326/169366449-11596cf4-6a64-4df2-8054-0f505581e049.png)

**Comment by Skeeve** [comment]
Try:

```html
<!-- Macro: :yes:
     Template: ac:status
     Title: "Yes"
     Color: "Green" -->

<!-- Macro: :no:
     Template: ac:status
     Title: "No"
     Color: "Red" -->
```
