### ISSUE TITLE
Is there any way to force the resulting Confluence tables to have specified widths?

### ISSUE THREAD

**Issue by BigBearBrian** [kovetskiy/mark#188]
I've tried coding in either <div> or <span> elements around my columns, a la [https://stackoverflow.com/questions/36121672/set-table-column-width-via-markdown](Stackoverflow). 

I also considered trying to use styles, but I don't see how to use Mark to set the "class" attribute on the individual columns.

**Comment by Skeeve** [comment]
I don't think so. Tables are generated by [blackfriday](https://github.com/russross/blackfriday) and this doesn't support it.

**Comment by kovetskiy** [comment]
You can try to wrap it in a div

```
<div style="width: 300px">

your table here

</div>
```

**Comment by Skeeve** [comment]
But this will not set column widths and as long as there is no way to include custom CSS into a confluence page, there won't be a way to style a column, I fear.

**Comment by BigBearBrian** [comment]
I ended up generating actual HTML tables instead of Markdown, and was able to successfully control the table's column width using (in Powershell):

`$setOutput +=  @"
<table data-layout="full-width" >
    <colgroup>
        <col style="width: 50.0px;" />
        <col style="width: 250.0px;" />
    </colgroup>

... insert table here using tr and td

</table>
"@`
