### ISSUE TITLE
Windows binary Issue

### ISSUE THREAD

**Issue by kevinneufeld** [kovetskiy/mark#19]
Building a native binary for windows, but the resulting binary have are not able to resolve page locations.

Steps
- cloned repo and built locally on mac and windows. 
- used your make file `make get` && `make build`

```shell
.\mark.exe -u $CONFLUENCE_CLOUD_ID_TC -p $CONFLUENCE_CLOUD_APIKEY_TC -l $CONFLUENCE_CLOUD_URL --dry-run --trace -f TestDoc-Readme.md
2020-03-20 16:39:07 [TRACE] loaded macro "@\\{([^}]+)\\}"
                            ├─ template: ac:link:user
                            ├─ expr: @\{([^}]+)\}
                            └─ config: map[Name:${1}]
2020-03-20 16:39:08  [WARN] page "Teamcity Build Agent" is not found
2020-03-20 16:39:08 [DEBUG] resolving page path: ??? > CICD > Teamcity Build Agent > TEST-Doc
2020-03-20 16:39:09 [FATAL] unable to resolve page location
                            └─ can't create ancestry tree: CICD > Teamcity Build Agent
                               └─ can't find root page for space "PSD"
                                  └─ no such space
```

Any insight into why the native windows binary fail to find the `space`? 

Thanks.

**Comment by kovetskiy** [comment]
Hi, it's definitely not platform-dependant issue, this error happens when confluence returns 404 while mark is trying to find such root page for space `PSD`.

Please make sure your confluence cloud URL includes /wiki at the end.

**Comment by kevinneufeld** [comment]
Thanks for getting back so quickly. It is a bit strange since the Alpine Image Container works as expected without issue same: document, base_url with /wiki and creds.  

When I try a native binary on Windows or Mac - mark fails to find the root page for PSD.
  
I am new to go and just got vscode debug working - hopefully stepping through will shed a bit of light. 

This is a great tool, awesome work, thanks again.

**Comment by kevinneufeld** [comment]
My bad - somehow I was using switch `-l` instead of `-b` for the baseUrl
