### ISSUE TITLE
Blanks in include filenames

### ISSUE THREAD

**Issue by Skeeve** [kovetskiy/mark#190]
In order to fix #189 I think this line
 
https://github.com/kovetskiy/mark/blob/5428cc683302a7679901e23d4e97fc83838a788b/pkg/mark/includes/templates.go#L21

Should be changed to

```go
	`(?s)<!--\s*Include:\s*(?P<template>.+?)\s*(\n(?P<config>.*?))?-->`)
```

**Comment by kovetskiy** [comment]
Closed with #191
