### ISSUE TITLE
Macros: Multiple uses of a macro replaces only one value in the template

### ISSUE THREAD

**Issue by kevinglasson** [kovetskiy/mark#20]
So what is happening is I'm trying to create a macro that will fill in relative links to other pages on our internal wiki.

It currently 'works' however it will fill all instances of the macro with the value that it first finds. I assume there is some hashmap in the program that is being populated with only one value?

I tried to have a look but I don't know go... anyway here is an example could you take a look and point me in the right direction in the codebase?

The template:

```html
<ac:link><ri:page ri:content-title="{{ .Page }}"/></ac:link>
```

The macro:

```markdown
<!-- Macro: \[WIKILINK\]\((.+)\)
     Template: templates/link.tmpl
     Page: ${1} -->
```

The input:

```markdown
[WIKILINK](Test page one)
[WIKILINK](Test page two)
```

The output:

```html
<ac:link><ri:page ri:content-title="Test page one"/></ac:link>
<ac:link><ri:page ri:content-title="Test page one"/></ac:link>
```

**Comment by seletskiy** [comment]
@kevinglasson: please try latest master, it should resolve the issue.

**Comment by kevinglasson** [comment]
@seletskiy: Yep, all working thank you!
