### ISSUE TITLE
Question: How to add columns/change page layout?

### ISSUE THREAD

**Issue by MattoHopkins** [kovetskiy/mark#208]
Trying to use this to create this layout:

![B97B951C-1263-47E1-A177-65998D71C5FC](https://user-images.githubusercontent.com/43736989/181153546-51601f50-b218-464f-8757-39be6b1980c1.jpeg)

Want a table of contents on the left column and the rest of the page on the right. Good chance i'm blind/stupid and have missed this, but don't see anything in the docs relating to this. Whether this is done via page layout or individual columns I'm not really that fussed, but thats the split/layout I'm after

Thanks for the help!

**Comment by stephenpaulger** [comment]
The way that worked for me was (after using the changes in this PR #401) to use the plain layout.

```markdown
<!-- Layout: plain -->

<!-- ac:layout -->
<!-- ac:layout-section type:two_left_sidebar -->
<!-- ac:layout-cell -->

Put your table of contents macro here.

<!-- ac:layout-cell end -->
<!-- ac:layout-cell -->

Put your content here.

<!-- ac:layout-cell end -->
<!-- ac:layout-section end -->
<!-- ac:layout end -->
```

**Comment by mrueg** [comment]
thanks @stephenpaulger ! It looks like this should help the author, so closing this issue.
