### ISSUE TITLE
Create a tagged release to allow 'mark' to be installed via GoBinaries.com

### ISSUE THREAD

**Issue by klauern** [kovetskiy/mark#21]
It would be nice to have a tagged version of this tool so it can be easily installed by the [GoBinaries](https://gobinaries.com) service:

https://gobinaries.com/

From the webpage:

> How does it work?
> Take for example you want to install @rakyll's fantastic HTTP benchmarking tool hey, to install the latest release you would run:
>
>    curl -sf https://gobinaries.com/rakyll/hey | sh
>
>This request fetches the latest tag from GitHub and responds with a shell script which performs a second request, populated with the resolved version and architecture as shown here:
>
>    https://gobinaries.com/binary/github.com/rakyll/hey?os=darwin&arch=amd64&version=v0.1.3
>
>The response of this request is a Golang binary compiled for the requested os, architecture, and package version. The result is cached in a CDN for subsequent requests.

**Comment by kovetskiy** [comment]
I'm closing the issue since I've added the tag, thanks again for the goreleaser action!
