### ISSUE TITLE
Table cell alignement?

### ISSUE THREAD

**Issue by Skeeve** [kovetskiy/mark#221]
How do you align table cells?

Usually it works like this:

```Markdown
Left | Left | Center | Right
-----|:-----|:------:|------:
Left | Left | Center | Right
<|<|<>|>
Left | Left | Center | Right
```

Left | Left | Center | Right
----|:-----|:-------:|------:
Left | Left | Center | Right
<|<|<>|>
Left | Left | Center | Right

But `mark`/`blackfriday`(?) seems to not know about it.

**Comment by Skeeve** [comment]
The issue is:

blackfriday generates `align="..."` while confluence requires `style="text-align: ...;"`.

I tried to create a pull request there.

I also did not yet figure out how to include my fork into my local version :( in order to check proper working.

**Comment by joyfulrabbit** [comment]
This is super duper slick.

**Comment by Skeeve** [comment]
Hi @mrueg. Some time ago mark used kovetskiy/blackfriday.

This changed now to the underlying rusross/blackfriday.

But it seems the repo is dead.

Nevertheless I opened a new pull request there to fix the cell alignement in tables. If we want this to work correctly, we should think about going back to (a new) kovetskyi/blackfriday fork, or take my fork of it.

**Comment by Skeeve** [comment]
Also @mrueg: According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td the align-property in cells is deprecated. But that's what blackfriday creates.

**Comment by mrueg** [comment]
I believe this got resolved. Feel free to reopen if this is still an issue.
