### ISSUE TITLE
Question: the visibility of using macros in Github .md files

### ISSUE THREAD

**Issue by ahmedloai** [kovetskiy/mark#225]
I would like to use the tool to publish the contents from Github to Confluence. However, we would like to keep Github also a source of Docs for whom using and reading directly from it. When i use some macro like ac:box the text stay visible and displayed in the .md file in Github. Is there a way to adapt? or hide some parts if that relevant to Confluence only ?

Thanks for support any way

**Comment by joyfulrabbit** [comment]
I have this exact same use case:

We are using Mermaid and rendering using ` ````mermaid ` to invoke the github plugin.
I'm trying to be able to see my mermaid diagrams in both github and confluence which is proving to be tricky.

**Comment by joyfulrabbit** [comment]
I had this issue with mermaid. This worked for me in my file header:

``` <!-- Include: ac:code --> ```

**Comment by mrueg** [comment]
Looks like this has been answered.  Thanks @joyfulrabbit
