### ISSUE TITLE
Label appear and disappear (PingPong)

### ISSUE THREAD

**Issue by ahmedloai** [kovetskiy/mark#226]
When using the meta-data  I noticed the following behaviour. 

- if the page does not has the label it is added correctly
- When i republish the same page again which already has a label A, it disappeared. 

Please, have check i could be an easy fix Bug

**Comment by guipaivanz** [comment]
This issue has been open for a year and a half. Is there any update?

**Comment by mrueg** [comment]
This might be resolved by #454 please report back if not.
