### ISSUE TITLE
SIGSEGV when specifying page url via -l option

### ISSUE THREAD

**Issue by varejjka** [kovetskiy/mark#228]
Hi! 
I do `mark -u <user> -p <password> -l 'https://<confluence_host>/pages/viewpage.action?pageId=<ID>' -f file.md`

Got:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7342df]

goroutine 1 [running]:
main.processFile({0x7ffce420a200, 0x9}, 0x442a31, {{0x7ffce420a200, 0x9}, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/mark/mark/main.go:208 +0x27f
main.main()
	/home/runner/work/mark/mark/main.go:159 +0x5fc

```

If i use metainfo and -b option all works fine

version 8.4 linux amd64

**Comment by joyfulrabbit** [comment]
I have the same issue. 

arm64, mark version 8.4, confluence 7.13.7
Go version go1.18.1 darwin/arm64

I see this issue has come up before, but there aren't a lot of details about the version of Confluence or the URL that was specified, or the config settings file etc.

**Comment by mrueg** [comment]
Please try again with a later version of mark and report back if the issue still exists.
