### ISSUE TITLE
Why is the required macro version of mermaid not specified in the documentation?

### ISSUE THREAD

**Issue by joyfulrabbit** [kovetskiy/mark#232]
I'm just curious why the documentation doesn't call out that a specific version macro is required in order for Mermaid to work? 

I was able to make some minor changes and get the variant I have installed to work but I feel like it might be worth mentioning that for best results you should install mermaid version X

**Comment by mrueg** [comment]
We now have another option with mermaid.go so I believe this issue can be closed.
