### ISSUE TITLE
Simple block quotes are no longer rendered properly in confluence with 8.6

### ISSUE THREAD

**Issue by danielloganking** [kovetskiy/mark#247]
## Bug

*Version Affected:* 8.6
*Does this exist in previous versions?* No

### Steps to Reproduce
1. Create the following markdown doc:
```markdown
# Test Doc for Blockquotes

## Simple Blockquote

> This paragraph is a simple blockquote
```
2. Publish the doc

*Expected Result:* Blockquote appears in `<blockquote>` HTML node
*Actual Result:* Blockquote renders as an error box with the text `📜Unknown Macro: 'none'` 

## Background

I am still in the process of debugging what exactly is occurring but, following an upgrade to 8.6, when publishing to confluence we now see an error box in any place in the document which uses "simple" blockquotes (ie `> some blockquote`). Downgrading to 8.5 resolved the issue and blockquotes returned to their normal appearance.

Assuming I do not get pulled in to other work my plan is to create some tesk markdown and compare the HTML output of 8.5 to 8.6 and dig into the code to understand why this regression occurred.

**Comment by mrueg** [comment]
The recent change on blockquotes I see is: https://github.com/kovetskiy/mark/commit/8c02497b5f192286eea4f51130a2a4a134c72966

Do multi-line block quotes still work?

@prokod are you able to help with this one?

**Comment by danielloganking** [comment]
Thank you for the quick fix🎉 I will test this on our doc where this was discovered later today.
