### ISSUE TITLE
Relative links support

### ISSUE THREAD

**Issue by khmelevskikh** [kovetskiy/mark#25]
Hi team,
And thank you for the awesome tool!
Do you have any plans to support relative link in articles? Or maybe it is already there, but I didn't get it?

Right now such type of links:
`[Configuration](docs/configuration.md)`
turns into 
`(https://<confluence_link>/display/<space_name>/docs/configuration.md)`

**Comment by kovetskiy** [comment]
Hi, currently it's not implemented, but I'd like to merge a pull request implementing this feature!
