### ISSUE TITLE
Version 8.9 breaks ability to have relative attachment paths

### ISSUE THREAD

**Issue by lucasoskorep** [kovetskiy/mark#263]
Not sure what the update was that did this, but for now ALL relative attachments fail to be resolved with confluence with the following error:

```
 FATAL unable to resolve relative links
                              └─ resolve link: "{attatment filename here}"
```

Version 8.8 and below has no issues with relative attachments. 

Looking into a fix and can provide more information if needed.

**Comment by mrueg** [comment]
Thanks for the report!
Do you have a minimal markdown example that you could share?

**Comment by lucasoskorep** [comment]
I have a fix but it looks like it just avoids some new logic.  

I have a folder structure as follows:

folder1/folder2/readme.md
folder1/folder2/image.png

readme.markdown lists its attachment:

`<!-- Attachment: image.png -->`

The last update of the code now passes in the file path base to the ResolveRelativeLinks call from main. 

This causes large issues  - previously this image file would stop at link 68 of link.go because ./image.png doesnt exist. 
Now however it finds the file, reads it, finds the title as part of a random string in the png file because it is highly likely to do so, and then assigns that to the metadata.title object and tries to find the confluence page for metadata.title. 

the title being extracted from my PNGs is usually along the lines of:
`extracted metadata: space= title=> <rdf:Description rdf:about=""/> </rdf:RDF> </x:xmpmeta>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <?xpacket end="w"?>��8Photoshop 3.08BIM8BIM%��ُ��      ���B~���ICC_PROFILE�applmntrRGB XYZ �
` 

This creates a fatal error when trying to find the confluence page.  

Not sure if reverting as my attached PR does is the correct solution, but it does work on my end again.

**Comment by lucasoskorep** [comment]
This is the core causing the error specifically:

`		if titleFromH1 && meta.Title == "" {
			meta.Title = ExtractDocumentLeadingH1(data)
		}
		
		
		...
		
		
		
// ExtractDocumentLeadingH1 will extract leading H1 heading
func ExtractDocumentLeadingH1(markdown []byte) string {
	h1 := regexp.MustCompile(`#[^#]\s*(.*)\s*\n`)
	groups := h1.FindSubmatch(markdown)
	if groups == nil {
		return ""
	} else {
		return string(groups[1])
	}
}

`

**Comment by mrueg** [comment]
Thanks for debugging it!

Do you only have the `<!--- Attachement: image.png -->` or are you referencing it later in the markdown?


I'm not sure if we should try to differ by file extension here, a solution could include https://pkg.go.dev/golang.org/x/tools/godoc/util?utm_source=godoc#IsTextFile so we at least skip binary files.

**Comment by lucasoskorep** [comment]
I would say some do and some do not reference it later in the markdown. I think I am seeing the issue with both.  

I liked the godoc https://pkg.go.dev/golang.org/x/tools/godoc/util?utm_source=godoc#IsText solution as we already have the file open and it simplifies needing a vfs.Opener to give to IsTextFile.   Changed my PR to support it - let me know what you think!
