### ISSUE TITLE
Link to Confluence page doesn't work with title that contains spaces

### ISSUE THREAD

**Issue by bernd** [kovetskiy/mark#272]
Using a `[](ac:...)` tag to link to a Confluence page doesn't work.

I don't know if that ever worked. But with the goldmark parser, the `renderLink` method is not called at all. I guess the parser doesn't see it as a `ast.Link` because of the whitespace.

It works when using the second form where the link test is equal to the page title.

Input:

```markdown
[A Test](ac:A Test)
[A Test](ac:)
```
Output:
```html
<p>[A Test](ac:A Test)</p>
<ac:link><ri:page ri:content-title="A Test"/><ac:plain-text-link-body><![CDATA[A Test]]></ac:plain-text-link-body></ac:link></a></p>
```

Is that something that worked before? Is there a known workaround? Thank you!

**Comment by mrueg** [comment]
From testing it, it looks like this was working before. Do you want to take a look at it?

**Comment by bernd** [comment]
@mrueg I will take a look.

The problem is that space characters are not allowed when using the `[text](destination)` syntax. 

> A [link destination](https://spec.commonmark.org/0.30/#link-destination) consists of either
> - a sequence of zero or more characters between an opening < and a closing > that contains no line endings or unescaped < or > characters, or
> - a nonempty sequence of characters that does not start with <, does not include [ASCII control characters](https://spec.commonmark.org/0.30/#ascii-control-character) or [**space**](https://spec.commonmark.org/0.30/#space) character, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

Source: https://spec.commonmark.org/0.30/#link-text

Spaces are only allowed when using the `[text](<destination>)` syntax. The following should work:

```
[A Test](<ac:A Test>)
```

It currently doesn't work because the pattern for the colon replacement in `<ac:... />` tags matches for that syntax. :smile: So we need to adjust that pattern.

So it's a backwards incompatible change because goldmark adheres to the spec and doesn't allow the old syntax.

What do you think?

**Comment by bernd** [comment]
> I think it might be better to extend the ast with a new kind and remove the hack that replaces the colon.

Agreed. That's a bit over my head, though. :sweat_smile:

**Comment by bernd** [comment]
> > I think it might be better to extend the ast with a new kind and remove the hack that replaces the colon.
> 
> Agreed. That's a bit over my head, though. sweat_smile

I will give it a shot anyways.

**Comment by mrueg** [comment]
Cool, thanks! You'd need to define an extension similar to
https://github.com/yuin/goldmark/blob/master/extension/ast/strikethrough.go
https://github.com/yuin/goldmark/blob/master/extension/strikethrough.go

**Comment by bernd** [comment]
> Cool, thanks! You'd need to define an extension similar to https://github.com/yuin/goldmark/blob/master/extension/ast/strikethrough.go https://github.com/yuin/goldmark/blob/master/extension/strikethrough.go

Thanks for the links! I created a PR with a first try: https://github.com/kovetskiy/mark/pull/273

**Comment by mrueg** [comment]
First try looks really good already! Thanks for your contribution
