### ISSUE TITLE
Several issues with Mark

### ISSUE THREAD

**Issue by AX-LLaidley** [kovetskiy/mark#290]
I've been working on setting up Mark to transfer Markdown docs to a Confluence space, and have found a few issues:

- Mark completely ignores the config file. The config file is located at the default location `~/.config/mark` however Mark doesn't load it. This results in having to include any options (including the username and token) on the command line itself. This is undesirable, as I'm planning to automate the transfer process using Github Actions, and I don't want to have to hard-code credentials into the action workflow (security risk).
- The options `title-from-h1` and `drop-h1` have no effect at all. If I remove the title from the frontmatter, Mark complains about the lack of a title. If I include the title in the frontmatter, in addition to the H1 in the document itself, I then end up with documents in the Confluence space that effectively have 2 titles.
- When I use the `ac:box` macro for admonition blocks, if the block also contains an unordered list, the block does not render in Confluence. I have tried using Markdown for the unordered list, as well as HTML, and even gone as far as to try to wrap the list in a `<span></span>` but nothing works. This is going to be a problem for us, because we have a large number of documents, and many of them contain admonition blocks that contain unordered lists.
- Using `<!-- Include: disclaimer.md -->` has no effect at all. The path to the `disclaimer.md` file is valid, and the file does exist. However, the text in the `disclaimer.md` is not actually included in the resulting docs in Confluence.

Not sure if it matters, but I'm running Mark on a M1 Macbook Pro, with Mark installed using Brew. Any ideas why I'm having these issues?

**Comment by mrueg** [comment]
Thanks for your report! To make it easier to follow-up on each of them, I would suggest to report each problem in a single issue and provide a minimal example for what is not working and parameters used, which exact version of mark you are using.  I've added an issue template in  https://github.com/kovetskiy/mark/pull/292 that will provide better guidance on reporting.

**Comment by AX-LLaidley** [comment]
Ok, I'll resubmit as separate issues and then close this issue. Thanks!

**Comment by AX-LLaidley** [comment]
See [297](https://github.com/kovetskiy/mark/issues/297), [298](https://github.com/kovetskiy/mark/issues/298), [299](https://github.com/kovetskiy/mark/issues/299)
