### ISSUE TITLE
Error with version 9.2

### ISSUE THREAD

**Issue by areichardt-apo** [kovetskiy/mark#293]
When using the latest docker image 9.2 i get the following error:

`Using docker image sha256:a4c7a0aa381b8727e818263a5f636ff99c4d9398ca5f10a8d22725ce143ff458 for kovetskiy/mark with digest kovetskiy/mark@sha256:e3632417e8ff7ef83eaab542ca56a9d602101ead7140abe569edb2aee9190d6a ...
[0426/071117.113712:ERROR:headless_shell.cc(255)] Multiple targets are not supported.`

We had to switch back to 9.1.4

**Comment by mrueg** [comment]
Thanks for the report, this should be fixed in 9.2.1

Please follow the issue template for the next report, it will make it easier to understand what's going on.
