### ISSUE TITLE
Commons clause license blocks mark from reaching more users

### ISSUE THREAD

**Issue by eliroca** [kovetskiy/mark#295]
Firstly, thank you for creating and maintaining Mark! It's awesome.
I package Mark for openSUSE distros – https://build.opensuse.org/package/show/home:eroca:go/mark.

Because of the "commons clause condition" added on top of Apache license, I am unable to submit Mark to the official openSUSE repositories, from where it could be installed by simply running `zypper install mark`.

The reason is SPDX rejecting to add the license: https://github.com/spdx/license-list-XML/issues/902

Maybe consider using an SPDX license for future releases? The benefit would be a potential increase in users, popularity, contributions?

**Comment by mrueg** [comment]
In #487 we replaced CC with Apache 2.0
