### ISSUE TITLE
Add toc macro support

### ISSUE THREAD

**Issue by teopost** [kovetskiy/mark#30]
Hi,
  I suggest adding the macro for "Table of Content"

This is metadata document page:
* https://confluence.atlassian.com/conf59/table-of-contents-macro-792499210.html

**Comment by seletskiy** [comment]
Hello,

Could you try to implement it in a PR?

It should be pretty straightforward to do:
* just add macro definition here using standard Go template syntax: https://github.com/kovetskiy/mark/blob/master/pkg/mark/stdlib/stdlib.go#L139;
* add doc entry to the README.

**Comment by teopost** [comment]
I don't know golang unfortunately, but the modification should be simple.
I tried to add the template as you suggested, but unfortunately it doesn't work.

I have added the toc macros here:
* https://github.com/teopost/mark/commit/d427af901daeda594ddcfb267391f3e1126eb84c

I use it this way

```
<!-- Macro: TOC
     Template: ac:toc
     Exclude: Summary -->

```

but it is not expanded in the html

Can you help me ?

PS: What do I need the first parameter "Macro:" ?

**Comment by seletskiy** [comment]
@teopost Hey, your commit looks OK.

To use the pre-defined macro you can use the following syntax:

* Without parameters:
  ```markdown
  <!-- Include: ac:toc -->
  ```


* With parameters:
  ```markdown
  <!-- Include: ac:toc
       Exclude: Summary -->
  ```

---

> PS: What do I need the first parameter "Macro:" ?

The macro syntax is used to define a shortcut for pre-defined macro (as can be seen in the examples section about referencing Jira issues) or to define a shortcut to the template.

So, the first parameter in macro is a regexp. It will be used to search and replace all occurences of the given regexp by the defined macro. You don't have to use it in your particular case.

It may be useful if you would like to define TOC without some section (say, summary) once and use it in all your documents later:

```markdown
<!-- Macro: TOC_NO_SUMMARY
     Template: ac:toc
     Exclude: Summary -->

TOC_NO_SUMMARY

rest of the document goes here
```

All occurences of `TOC_NO_SUMMARY` in the document will be replaced with your defined macro.

**Comment by teopost** [comment]
it works! 
I will do pool request
Thank you.
