### ISSUE TITLE
The mark help in application (mark -h) is much more up to date than what is shown in the github readme.md

### ISSUE THREAD

**Issue by joyfulrabbit** [kovetskiy/mark#310]
**What happened?**
You updated the help menus on the application, but it isn't updated on the github readme.

**What did you expect to happen?**
Parity.

**How can we reproduce the behavior you experienced?**
mark -h  and compare to readme.md on github

Update yer readme :) ;)  :)

**Comment by joyfulrabbit** [comment]
[PR312]

**Comment by mrueg** [comment]
Thanks, merged your PR
