### ISSUE TITLE
Add support for named excerpts

### ISSUE THREAD

**Issue by chipbite** [kovetskiy/mark#316]
**Is your feature request related to a problem? Please describe.**
Support for named excerpts, which enable a confluence page to define several excerpts exposed for other pages to include.

**Describe the solution you'd like**
The excerpt and excerpt-include macros add name attribute to support named excerpts.

**Describe alternatives you've considered**
Only using one excerpt per page.

Ref: https://github.com/kovetskiy/mark/pull/277

**Comment by mrueg** [comment]
This is fixed in https://github.com/kovetskiy/mark/commit/3d96781f477d02c341d70d9c434b8480d688027d
