### ISSUE TITLE
@{Name} fails on versions after v9.4.0

### ISSUE THREAD

**Issue by jphastings** [kovetskiy/mark#327]
**What happened?**
While attempting to deploy a markdown file with only `@{Existing Person Name}` to Cloud Confluence, using mark `v9.5.2` I receive this error:

```
INFO  processing test.md
FATAL unable to execute macros template
     └─ template: ac:link:user:1:80: executing "ac:link:user" at <.AccountID>: can't evaluate field AccountID in type string
```

This error does not occur with mark `v9.4.0`.

**What did you expect to happen?**
I expected a user link macro to be present on a page deployed to Confluence.

**How can we reproduce the behavior you experienced?**
1. Create a markdown file containing `@{Your Name}` called `test.md` (Where a person called `Your Name` exists in that Confluence)
2. Assuming `.config/mark` contains all required auth config:
  a. With Mark v9.5.2 run: `mark -f test.md` — witness failure
  b. With Mark v9.4.0 run: `mark -f test.md` — witness success

In case this is related to specific markdown, please provide a minimal markdown example here.

**Information (please complete the following information):**
 - Mark Version (`mark --version`): v9.5.2
 - Mark Parameters: none beyond auth
 - Confluence Version: Confluence Cloud
 - Environment specific Information: tested on mac OS (M1/arm64), and Github Actions ubuntu-latest (x86)

**Logs or other output**
```
INFO  processing test.md
FATAL unable to execute macros template
     └─ template: ac:link:user:1:80: executing "ac:link:user" at <.AccountID>: can't evaluate field AccountID in type string
```

**Additional context**
n/a

**Comment by mrueg** [comment]
@jphastings can you try building #328 and see if this fixes it for you?

**Comment by mrueg** [comment]
Please test with 9.6.0 and feel free to reopen if it is still failing.
