### ISSUE TITLE
Panel Macro

### ISSUE THREAD

**Issue by kedarv** [kovetskiy/mark#333]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use the Panel Macro: https://confluence.atlassian.com/conf717/panel-macro-1115675967.html

Is it possible within the current constructs of the macro syntax? or would it need to be implemented?

**Comment by mrueg** [comment]
I've added a macro in https://github.com/kovetskiy/mark/pull/337 please give it a try.

**Comment by kedarv** [comment]
Thanks @mrueg , I was able to get a basic example working. But, I'm not sure how to construct the Macro such that I can include "complex" content inside of it, like lists and text line breaks. Here is how I am using the Macro so far:

```
<!-- Macro: :panel:([^:]+):([^:]+):(.+):(.+):(.+):(.+):
     Template: ac:panel
     Title: ${1}
     Body: ${2}
     BGColor: ${3}
     TitleBGColor: ${4}
     TitleColor: ${5}
     BorderStyle: ${6} -->
```

`:panel:some title:some body content:#FAF9F8:#3178C6:#FFFFFF:none:`

am I misunderstanding how to use macros? I would like to do something like
```
:panel:some title:some body 
- a
- b
- c
:#FAF9F8:#3178C6:#FFFFFF:none:```

**Comment by sheldonhull** [comment]
@kedarv did you ever figure out how to do what you mentioned here?

**Comment by kedarv** [comment]
> @kedarv did you ever figure out how to do what you mentioned here?

not really :/ I ended up just using the raw confluence markup in my documents

**Comment by sheldonhull** [comment]
Mind sharing a snippet? I tried multline in a few ways to create a custom panel and couldn't get it to work.

**Comment by kedarv** [comment]
ah I'm misremembering what I used confluence markup for, it was for `<ac:structured-macro ac:name="expand">` but I imagine the panel/alert should work similarly
