### ISSUE TITLE
Linked blog certificate has expired

### ISSUE THREAD

**Issue by awilkins** [kovetskiy/mark#339]
The cert for samizdat.dev has expired ; more than a couple of weeks ago now, so I guess your ACME client has stalled.

In the meantime I shall be reading the documentation instead :-)

**Comment by mrueg** [comment]
Looks like TLS cert is valid again. Thanks for letting us know!

**Comment by austince** [comment]
This seems to have happened again, invalid as of June 4th
<img width="1067" alt="image" src="https://github.com/kovetskiy/mark/assets/4655775/257ad5aa-04b6-4fb8-858f-e0937d5c852c">
