### ISSUE TITLE
os.Getenv("HOME") need not be the homedirectory

### ISSUE THREAD

**Issue by Skeeve** [kovetskiy/mark#352]
In `main.go` there are three locations where the user's homedirectory is required.

- https://github.com/kovetskiy/mark/blob/295d17e6f30452127d1032e9c57ca6d55700eef7/main.go#L128C1-L129C1
- https://github.com/kovetskiy/mark/blob/295d17e6f30452127d1032e9c57ca6d55700eef7/main.go#L185C38-L185C55
- https://github.com/kovetskiy/mark/blob/295d17e6f30452127d1032e9c57ca6d55700eef7/main.go#L189C56-L189C73

Since I wanted to enhance template inclusion by allowing `~/` I also required the homedirectory. So I searched and found this:

https://stackoverflow.com/questions/7922270/obtain-users-home-directory

Since go 1.12 the recommended way is:

```go
package main
import (
    "os"
    "fmt"
    "log"
)
func main() {
    dirname, err := os.UserHomeDir()
    if err != nil {
        log.Fatal( err )
    }
    fmt.Println( dirname )
}
```

Shouldn't we change accordingly?

**Comment by mrueg** [comment]
Good catch, yes please use https://pkg.go.dev/os#UserHomeDir

**Comment by Skeeve** [comment]
Maybe even better:

func [UserConfigDir](https://cs.opensource.google/go/go/+/go1.21.1:src/os/file.go;l=460) [¶](https://pkg.go.dev/os#UserConfigDir)
added in go1.13

> func UserConfigDir() ([string](https://pkg.go.dev/builtin#string), [error](https://pkg.go.dev/builtin#error))
> UserConfigDir returns the default root directory to use for user-specific configuration data. Users should create their own application-specific subdirectory within this one and use that.
> 
> On Unix systems, it returns $XDG_CONFIG_HOME as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.config. On Darwin, it returns $HOME/Library/Application Support. On Windows, it returns %AppData%. On Plan 9, it returns $home/lib.
> 
> If the location cannot be determined (for example, $HOME is not defined), then it will return an error.

**Comment by mrueg** [comment]
That sounds great as well! :)
