### ISSUE TITLE
Inline Macros do not work as described.

### ISSUE THREAD

**Issue by Skeeve** [kovetskiy/mark#361]
**What happened?**

It seems a breaking change was introduced.

An inline-macro example from the readme does not work anymore:

```
  <!-- Macro: <tblbox\s+(.*?)\s*>
       Template: #inline
       title: ${1}
       inline: |
           <table>
           <thead><tr><th>{{ .title }}</th></tr></thead>
           <tbody><tr><td>
        -->
  <!-- Macro: </tblbox>
       Template: #also_inline
       also_inline: |
           </td></tr></tbody></table>
        -->
  <tblbox with a title>
  and some
  content
  </tblbox>
```

It produces

```html
  <table>
<thead><tr><th>{{ .title }}</th></tr></thead>
<tbody><tr><td>
<p>and some
content</p>
  </td></tr></tbody></table>
```

**What did you expect to happen?**

It should have replaced the `{{ .title }}`

```html
  <table>
<thead><tr><th>with a title</th></tr></thead>
<tbody><tr><td>
<p>and some
content</p>
  </td></tr></tbody></table>
```

**How can we reproduce the behavior you experienced?**

1. Create an md file with the inline macro
2. Run mark --dry-run -f filewithmacro.md

** Information (please complete the following information):**
 - Mark Version (`mark --version`): 9.9.0
 - Mark Parameters: irrelevant I guess
 - Confluence Version: irrelevant as the dry run output needs to be checked
 - Environment specific Information: Mac OS 13.5.2

**Comment by Skeeve** [comment]
Seems to be a side effect of another macro I use.

Closing for now

**Comment by wrbbz** [comment]
@Skeeve, do you remember what macro had a side effect on this?

I was tried to add inline macro to the already created page and got `<no value>` on regexp capture groups.
However, on newly created page everything is fine

**Comment by Skeeve** [comment]
> [@Skeeve](https://github.com/Skeeve), do you remember what macro had a side effect on this?
> 
> I was tried to add inline macro to the already created page and got `<no value>` on regexp capture groups. However, on newly created page everything is fine

Sorry, no. I can't.

**Comment by wrbbz** [comment]
Well, thank you anyway
