### ISSUE TITLE
Broken Syntax on 9.10.0 from 9.9.0

### ISSUE THREAD

**Issue by lucasoskorep** [kovetskiy/mark#380]
**What happened?**
9.10.0 breaks compatibility with existing docs. 

Several things have broken in 9.10.0 including:

- Checklists (markdown checklists generate 400s from confluence )
- Italics (specifically anything italic with a period at the end followed by _ or * will fail)
- The long dash `—` has been broken even though it is valid markdown
- Others I am probably missing

**What did you expect to happen?**
Similarly to version 9.9.0 I expected eveything to just be uploaded and work

**How can we reproduce the behavior you experienced?**
1. add any of the above valid markdown which used to work to a markdown file 
2. attempt upload to confluence

** Logs or other output**
2023-10-20 16:24:45.546 FATAL Confluence API returned unexpected status: 400 Bad Request, output: ""

**Additional context**
will post whatever is needed.  Tried it on a fresh document and repository with each of the above samples

**Comment by kedarv** [comment]
I noticed even line breaks like 
`***` are broken

**Comment by mrueg** [comment]
Is this confluence cloud, server or datacenter? And which confluence version?

**Comment by lucasoskorep** [comment]
confluence cloud

**Comment by kedarv** [comment]
seeing the issue on confluence server

**Comment by mrueg** [comment]
https://github.com/kovetskiy/mark/releases/tag/9.10.1 Please test with this release and report back if it's not working.

**Comment by lucasoskorep** [comment]
@mrueg works great now - thank you!
