### ISSUE TITLE
Problem using the mark image in Github Actions

### ISSUE THREAD

**Issue by AbianG** [kovetskiy/mark#41]
I implemented a pipeline for Bitbucket using Mark (image: kovetskiy/mark). Then I tried the same on Github and when the pipeline (actions there) runs I get the following error:

`No runner matching the specified labels was found: kovetskiy/mark.`

Seems like the image for mark is not present in Github, but I find it weird, I though if it was present in Bitbucket it would be on Github. So, there's surely something I'm missing.

**Comment by kovetskiy** [comment]
Could you submit an example of the workflow?

**Comment by AbianG** [comment]
It was a problem with Github-specific config in the .yml. Fixec now!
