### ISSUE TITLE
Reference article is no more accessible

### ISSUE THREAD

**Issue by mpagot** [kovetskiy/mark#424]
## What happened?

The readme cite an external article: https://samizdat.dev/use-markdown-for-confluence/  

Due to a certificate issue, it is no more accessible.

## What did you expect to happen?

Be able to read the article

## How can we reproduce the behavior you experienced?

Try open https://samizdat.dev/use-markdown-for-confluence/ in any browser

**Comment by stephenpaulger** [comment]
https://web.archive.org/web/20231210204843/https://samizdat.dev/use-markdown-for-confluence/

Archived version may be useful as a workaround.

**Comment by stephenpaulger** [comment]
@mrueg this should be closable now.

**Comment by mrueg** [comment]
Thanks, yes you're right
