### ISSUE TITLE
Blockquote note/warn macros not working

### ISSUE THREAD

**Issue by markstickley** [kovetskiy/mark#446]
## What happened?

When writing warn and note macros, I'm seeing some incorrect behaviour. Info seems to be OK.

E.g.

```
> Warn
> This is a styled blockquote using the info macro
```

## What did you expect to happen?

I expected to see a styled blockquote in Confluence using the relevant macro. Using Note seems to generate a Warn style; using Warn generates an error

```
> Note
> This is a test
```
generates:
<img width="361" alt="image" src="https://github.com/kovetskiy/mark/assets/83684/e2370c76-a4e7-402e-a4d4-843451fda75f">

```
> Warn
> This is a test
```
generates:
<img width="239" alt="image" src="https://github.com/kovetskiy/mark/assets/83684/3128377c-96fe-48d4-86c2-b3da3a6d6109">

## How can we reproduce the behavior you experienced?

Paste the above examples into a markdown document and convert / publish to confluence.

## Further Information (please complete the following information)

* Mark Version (`mark --version`): v9.12.0
* Mark Parameters: Using config file (see below)
* Confluence Hosting: Cloud
* Confluence Version: Cloud
* Environment specific Information: Running locally on Mac OS using version installed from homebrew

## Logs or other output

```
% mark -c ~/.mark -f ./developer-guide/README.md
2024-05-23 16:54:26.041 INFO  processing developer-guide/README.md
2024-05-23 16:54:27.004 INFO  page will be stored under path: Overview >  Developer Guide
2024-05-23 16:54:27.203 INFO  the leading H1 heading will be excluded from the Confluence output
2024-05-23 16:54:27.959 INFO  edit locked on page "Developer Guide" by user "email@domain.com" to prevent manual edits
2024-05-23 16:54:28.362 INFO  page successfully updated: https://mysite.atlassian.net/wiki/spaces/~123456789/pages/3227386973/Developer+Guide
https://mysite.atlassian.net/wiki/spaces/~123456789/pages/3227386973/Developer+Guide
```

## Additional context

Config file:
```
username = "email@domain.com"
password = "API key"
base-url = "https://mysite.atlassian.net/wiki"
title-from-h1 = true
drop-h1 = true
space = "~123456789"
edit-lock = true
```
---

Edit: The same is happening when using the [box macro](https://github.com/kovetskiy/mark?tab=readme-ov-file#insert-colored-text-box) mentioned in the docs with the addition of the `Tip` version looking like Confluence's "Success" info panel.

**Comment by mrueg** [comment]
I believe this will be fixed in https://github.com/kovetskiy/mark/pull/496
