### ISSUE TITLE
Support for ```graphql

### ISSUE THREAD

**Issue by neerup** [kovetskiy/mark#463]
Hi 

It would be great if support could be added for 
Graphql

```graphql
type Mutation {
}
```

Just like the current support for XML
```xml
<xml>value</xml>
```

**Comment by mrueg** [comment]
I don't understand how mark could support this. Could you explain this further?

**Comment by neerup** [comment]
Sure...
In Markdown You can display xml using 
```code
starting with ```xml and ending with same 3 `
<xml>text</xml>
```
This is translated into confluence using mark showing the xml beautifully using the code block macro.

It would be nice if the same support could be made for GraphQl, but writing this I see that the macro does not support GraphQl... Sorry

**Comment by mrueg** [comment]
Closing this as the macro doesn't support graphql.
