### ISSUE TITLE
Possibility not to update the page if unresolved inline comment exists

### ISSUE THREAD

**Issue by qmg-krewera** [kovetskiy/mark#478]
**Is your feature request related to a problem? Please describe.**
Business users may leave the inline comments on confluence as feedback related to the content. Having a flag allowing to skip (and report) page where unresolved comments exist would be a safe net allowing to spot feedback, address it, resolving and then to generate confluence content again using `mark`.

**Describe the solution you'd like**
`mark` allows to set a flag (`skip-commented-pages` for example) which would result in checking if page which is about to be updated has any unresolved comment. If so, `mark` reports such page, but leaves the content unchanged. That would give a way to spot inline comments left by confluence content consumers and allow to address the feedback. Not having the flag set would result in page's content replaced, together with inline comment. 

**Describe alternatives you've considered**
Manual scanning of generated confluence pages before republishing the content using `mark`.

**Comment by mrueg** [comment]
Is there a way in the API to check if a page has comments received?
