### ISSUE TITLE
Line breaks are not working at all

### ISSUE THREAD

**Issue by trkas** [kovetskiy/mark#480]
## What happened?

Line breaks are not working at all 

## What did you expect to happen?

I have a README.md file containing: 

> 
> 
> 
> 
> 
> 
> <p style="display: none">
> :box:warning:Do not maintain in Confluence:This document should only be maintained through the <a href="https://github.com/EG-A-S/ng-template-standard-app/blob/main/README.md">README.md</a> file in the ng-template-standard-app project:
> </p>
> 
> # Creating a new app from template
> 
> Template for a ASPECT4 Standard NextGen app with the standard layout
> 
> This template project is for creating standard apps.
> 
> It's based on a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).

After uploading to confluence with v10.0.0, it doesn't show the confluence page correctly. the 3 lines are just showing as 1 line.

## How can we reproduce the behavior you experienced?

just run the content described above and run it with mark v10.0.0.

 I am using a Github workflow:

docker run --rm -v $(pwd):/tmp -i kovetskiy/mark:latest mark -p ${{ secrets.A4_CONFLUENCE_PAT }} -b https://confluence.eg.dk --h1_title --h1_drop -f /tmp/$file || true

if i use v9.13.1, it works:

docker run --rm -v $(pwd):/tmp -i kovetskiy/mark:9.13.1 mark -p ${{ secrets.A4_CONFLUENCE_PAT }} -b https://confluence.eg.dk --h1_title --h1_drop -f /tmp/$file || true

## Further Information (please complete the following information)

* Mark Version (`mark --version`):  v10.0.0
* Mark Parameters: `--h1_title --h1_drop`
* Confluence Hosting: [e.g. Cloud, Server or Datacenter]
* Confluence Version:  8.5.9
* Environment specific Information: running in Github Actions

**Comment by mrueg** [comment]
I had removed paragraph support in v10 because it would work better with macros. We'll need to find a way to support both.
