### ISSUE TITLE
Add mermaid support

### ISSUE THREAD

**Issue by Vayrn** [kovetskiy/mark#49]
Hello !

It could be great that [mermaid](https://mermaid-js.github.io/mermaid/#/) graphs could be rendered as images for example when detected. Currently it does render plain text cause confluence doesn't support it.

**Comment by kovetskiy** [comment]
Hi

This would be a huge amount of work to do, but you can insert pre-rendered
mermaid graphs as images while storing them in the same directory.

**Comment by awwaiid** [comment]
Another approach would be to pre-process the `.md` files outside of `mark`, extracting out embedded mermaid or other commands and replacing them with image referencing the mermaid output.

**Comment by ingo** [comment]
As a different approach, you could drop the mermaid.js javascript into the markdown and wrap that in an HTML macro. I just can't figure out how to include an HTML macro. Suggestions?

<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});
</script>

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Have you tried with something like
```
<iframe class="render-viewer" sandbox="allow-scripts allow-same-origin allow-top-navigation" src="https://viewscreen.githubusercontent.com/markdown/mermaid?color_mode=dark&amp;azure_maps_enabled=true#0df8ce10-5cd4-4b0c-9d7f-" name="0df8ce10-5cd4-4b0c-9d7f-" data-content="{&quot;data&quot;:&quot;flowchart RL\n    a --entry--&amp;gt; b\n        flavour2_dynamic -..- \n&quot;}">
        </iframe>
```
?
