### ISSUE TITLE
Add command line option to disable Notify Watchers

### ISSUE THREAD

**Issue by Thomas-Haase** [kovetskiy/mark#50]
This is really a great tool 👍 
Do you see any chance to add command line options to disable 'Notify Watchers'?
Whe uploading new pages, otherwise two emails are sent to all watchers of the complete space: One create page mail, and one edit page mail. 
We woul like this tool to bulk upload tons of generic pages. We have customers that are watching the complete space and they get spammed by tons of emails form confluence.
(off topic: same issue when using the out-dated WebDAV access for uploading generic pages).

**Comment by Thomas-Haase** [comment]
May be, information from this (old, 2015) post is helpful.
https://jira.atlassian.com/browse/CONFSERVER-38804?error=login_required&error_description=Login+required&state=8a14fc02-45ef-4a57-8744-11c2f1d061b5

**Comment by kovetskiy** [comment]
Hey there, I'll be glad to merge a Pull Request that adds this feature.
