### ISSUE TITLE
Mark assumes page title is unique in space

### ISSUE THREAD

**Issue by winmillwill** [kovetskiy/mark#524]
## What happened?

When running mark to create a new page with a unique combination of ancestors and title, if a page with the same title already exists in the confluence space, mark fails with an error reporting that the given ancestors for the new page do not match the ancestors of the existing page.

## What did you expect to happen?

Running mark in this case would find however many existing pages with the same title and different ancestors and interpret them as having distinct identity from each other and from the page being created/updated, and would therefore create a new page without error and would similarly succeed with subsequent updates to any of the existing pages.

## How can we reproduce the behavior you experienced?

1. Create a page in space S with title T and ancestry A
2. Run mark to create another page in space S with title T and any ancestry that is not exactly A

## Further Information (please complete the following information)

```
mark --username bot.confluence.github@pantheon.io --password *** --space Catalog --title-from-h1 --files ./README.md --base-url https://getpantheon.atlassian.net/wiki --parents Component:endpoint-dragons --dry-run

2024-09-04 13:02:53.534 INFO  processing README.md
2024-09-04 13:02:53.998 FATAL unable to resolve page location
                              └─ unexpected ancestry tree, did not find expected parent page in the tree
                                 ├─ expected parent: Component:endpoint-dragons
                                 └─ list: Catalog Home; Component:cos-daemonsets
```

^^ in this case, a colleague is attempting to just move a file from one repo/directory to another, which we reflect in an ancestry change, but the same issue emerges if multiple repos have a standard doc with a standard title. It's not practical for us to have a separate confluence space for every repo.

mark version 9.10.1

**Comment by mrueg** [comment]
You can use https://github.com/kovetskiy/mark/pull/509 to create unique titles.

**Comment by mrueg** [comment]
I assume that resolves your request, if not let me know otherwise.
