### ISSUE TITLE
 FATAL Confluence API returned unexpected status: 400 , output:

### ISSUE THREAD

**Issue by prokod** [kovetskiy/mark#54]
Hi,

When trying to run mark tool the above message in the title appears after
```
INFO  page will be stored under path: ...
```
The page is created with the correct title but it is empty.
Is there some compatibility matrix with Confluence ? We use Confluence enterprise.

Seems like a great tool ! - I hope this specific issue is solvable

**Comment by prokod** [comment]
So I found out that the on of the culprits is `</br>` removing helped to avoid that error

**Comment by kovetskiy** [comment]
@prokod hey, you should try to run it with `--trace` and check the error Confluence returns. What do you mean by confluence enterprise? Confluence Server? If so, then it should work.

**Comment by prokod** [comment]
Hi @kovetskiy ,

I have issued the command with --trace and this is what I got back that seems relevant:
```
{"statusCode":400,"data":{"authorized":false,"valid":true,"allowedInReadOnlyMode":true,"errors":[],"successful":false},"message":"Error parsing xhtml: Unexpected close tag </br>; expected </p>.\n at [row,col {unknown-source}]: [11,7]","reason":"Bad Request"}
```

As I said removing `</br>` tag eliminates the issue

**Comment by kovetskiy** [comment]
I'm still not sure I correctly understand your issue, do you explicitly write `</br>` somewhere in your markdown file?

**Comment by prokod** [comment]
@kovetskiy Yes I use explicitly such tags to force sometimes line break.

**Comment by kovetskiy** [comment]
@prokod I see. The `br` tag doesn't have the closing option `</br>`. It's *Void Element*. Just use `<br>` where you need it without closing the tag.

https://dev.w3.org/html5/html-author/#void

**Comment by prokod** [comment]
I wouldn't close it yet :) The error is still there even you change `</br>` with `<br>`
The only way to "fix" that is tp do `<br></br>`
So it seems to me it could be improved.

Thanks anyways for the great tool!

**Comment by kovetskiy** [comment]
Hey, `<br />` works for me without issues on Confluence cloud.
