### ISSUE TITLE
Regression when rendering links with unusual content

### ISSUE THREAD

**Issue by Thomas-Haase** [kovetskiy/mark#64]
With my Markdown files I see a regression in 5.0. In the previous releases 4.4, 4.3 and 4.2 I got rendered results as expected. I have a link on page 1 to some header on page 2.
With 5.0 this link on page 1 is rendered e.g. as `v71)`, and the appearance of the closing round bracket is the regression.
My Markdown on page 1 is:
`[v71](Page2#Page2-Releasev71-22-Feb-2018(intern)) `
The link destination is a Markdown header on page 2, which is as follows:
`#### Release v71 - 22-Feb-2018 (intern) `

I admit, having this round brackets in the header links is probably not the best an most fail-safe idea, but it did work as expected in 4.4 and its predecessors.

**Comment by kovetskiy** [comment]
This is related to the regression in blackfriday. I've sent a patch to blackfriday's upstream.

For now, you can just escape the closing paren with a backslash.

https://github.com/russross/blackfriday/pull/679

**Comment by kovetskiy** [comment]
We'll go with my fork for now, doesn't look like russross has enough time for merging contributions right now.
The issue should be fixed in v5.2.

**Comment by Thomas-Haase** [comment]
Yes, I can confirm, that it is fixed.
