### ISSUE TITLE
Regression with code blocks

### ISSUE THREAD

**Issue by Tailzip** [kovetskiy/mark#65]
Hi,

Since version 4.2, code blocks are **always** wrapped into an expand block. Not matter if `collapse` is set or not.

I believe regression has been introduced with PR #60.

Here's some console outputs:

**In version 4.1:**
![mark-4 1](https://user-images.githubusercontent.com/1068018/106770974-cab81800-663e-11eb-8f57-9113f7779359.png)

**In version 5.0:**
![mark-5 0](https://user-images.githubusercontent.com/1068018/106770983-cc81db80-663e-11eb-8daa-b4f7be3e46ff.png)

**Comment by kovetskiy** [comment]
I've fixed it in v5.1, please try now.

**Comment by Tailzip** [comment]
It works, thanks!
