### ISSUE TITLE
Command should ask password than passing to parameter

### ISSUE THREAD

**Issue by weichuliu** [kovetskiy/mark#66]
`mark` only accepts `-p` for password.

If you pass the password to `mark` as argument, there will be security concerns.

- It's easy to leave the password in the shell history
- When `mark` is running, anyone can see your password with `ps aux`.

A better way is to prompt up and ask for password.

**Comment by kovetskiy** [comment]
You can specify `-` for `-p` and mark will read password from stdin.

Introduced in #62

**Comment by weichuliu** [comment]
That is nice to know.
It'll be great if this is mentioned in.
