### ISSUE TITLE
Error "invalid character '<' looking for beginning of value when resolving page

### ISSUE THREAD

**Issue by AbianG** [kovetskiy/mark#67]
Mark is giving an invalid character error that I cannot pinpoint, it seems it detects an invalid '<' char, but per documentation, thats precisely the first value that it needs in order to have the tags to point to the space, parent pages and title of the page itself. 

The page is pretty blank as its a test still:
```
<!-- Space: SITEOPS -->
<!-- Parent: SiteOperations -->
<!-- Title: Documentation -->

# Main documentation page for...
This is to be completed
```
The error that I get when running the following command `mark -u $MARK_USER -p $MARK_PASS -b $MARK_URL -f $file -k --trace || exit 1;` is:
```
2021-02-09 15:03:27.913 FATAL unable to resolve page
                              └─ error while finding page "Coolbox Documentation"
                                 ├─ invalid character '<' looking for beginning of value
                                 └─ title: Coolbox Documentation
```

**Comment by kovetskiy** [comment]
Try to enable --trace and check what's going on. But I'd bet < means Mark
expected JSON but received a document starting with <, which means it's
HTML.

**Comment by AbianG** [comment]
I do not understand. I pass a .md file with just the specified content in the comment above. Where is it exactly recieving HTML/JSON? (I ran it with --trace but I can't identify errors)

**Comment by kovetskiy** [comment]
```
2021-02-09 15:03:27.913 FATAL unable to resolve page
                              └─ error while finding page "Coolbox Documentation"
                                 ├─ invalid character '<' looking for beginning of value
                                 └─ title: Coolbox Documentation
```
Mark tried to read the server's response and expected JSON but got HTML, you should see HTML in logs. It could happen by a few reasons such as an incorrect url, bad request, or even bad auth credentials.

**Comment by AbianG** [comment]
Indeed, it was an invalid URL for the confluence wiki root. Issue is now fixed (and it was, indeed, user error 😅. BTW could you specify which permissions are needed in confluence to use the -k option in mark successfully? I got a permissions error when using it:

`2021-02-10 09:40:38.926 FATAL Confluence API returned unexpected status: 403 Forbidden, output: "{\"statusCode\":403,\"data\":{\"authorized\":false,\"valid\":false,\"errors\":[{\"message\":{\"translation\":\"Not enough permissions to alter ContentRestrictions on a content with ContentId <1385660479>\",\"args\":[]}}],\"successful\":false},\"message\":\"com.atlassian.confluence.api.service.exceptions.PermissionException: Not enough permissions to alter ContentRestrictions on a content with ContentId <1385660479>\"}"`

**Comment by kovetskiy** [comment]
> BTW could you specify which permissions are needed in confluence to use the -k option in mark successfully? 
I actually don't know for sure what permissions exactly are required for that.
But I think you should start from here and check other links on that page https://confluence.atlassian.com/doc/page-restrictions-139414.html

**Comment by Jikodis** [comment]
In my case, I was getting this error because I needed to be on my company's VPN to be able to successfully authenticate with my PAT.
