### ISSUE TITLE
Installing via go get broken

### ISSUE THREAD

**Issue by mborejdo** [kovetskiy/mark#71]
I am a complete go noob, but it seems, I cannot install mark via the mentioned go get method.

I see
```
go: downloading github.com/kovetskiy/mark v0.0.0-20210225050715-398cc7375e40
go get: github.com/kovetskiy/mark@none updating to
        github.com/kovetskiy/mark@v0.0.0-20210225050715-398cc7375e40 requires
        github.com/russross/blackfriday/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

This seems to be related to https://github.com/golang/go/issues/30354

**Comment by kovetskiy** [comment]
Should be fixed now, I removed the replace directive. Try with `go get -v -u github.com/kovetskiy/mark`

**Comment by mborejdo** [comment]
great that works! Thanks a lot.
