### ISSUE TITLE
Include does not work

### ISSUE THREAD

**Issue by tillepille** [kovetskiy/mark#74]
When trying the example from the readme I encounter an 
```
$ tree .
.
├── disclaimer.md
└── test.md
$ cat test.md
<!-- Include: disclaimer.md -->
<!-- Title: Test -->

# this is a test
file

$ mark <options> --dry-run
ERROR encountered unknown header "Include" line: "<!-- Include: disclaimer.md -->"
```

Is this due <https://github.com/kovetskiy/mark/blob/bf4bbbe20aec82872460cb7249cce286360e30bd/pkg/mark/meta.go#L22> is missing an `HeaderInclude`?

```
$ mark -v
5.2.1
```

does happen with docker container also.

**Comment by kovetskiy** [comment]
Thanks, should be fixed now
