### ISSUE TITLE
Quote symbol is converted automatically

### ISSUE THREAD

**Issue by weichuliu** [kovetskiy/mark#75]
Hi, recently I found that the pages synced by `mark` onto Confluent are displaying different quote symbol than the original md:

In the md file, It's `'` and `"`, and on the Confluent page, it is smartly converted into `‘ ’` and `“”`.

It's really smart but unwanted. I am not sure whether the conversion occurs on `mark` side or Confluent side.

Will be nice if there is a way to disable the conversion.

**Comment by kovetskiy** [comment]
Hey, I don't think mark does it, but you can check it on your own. You can run mark with the `--trace` mode and you will see what it sends to the confluence API.

**Comment by weichuliu** [comment]
Got it, thanks for confirmation and pointing the troubleshooting direction.
