### ISSUE TITLE
Add support for Confluence blog posts

### ISSUE THREAD

**Issue by mrdavidlaing** [kovetskiy/mark#78]
I'd like to see support for converting markdown files to Confluence Blog posts added to `mark`

I imagine it would work by extended the "standard" page functionality to include a Type metadata header; ala:

```
<!-- Space: TEST -->
<!-- Type: blogpost -->
<!-- Title: My Blog post -->

This is my blog post.
```

Is this something on the roadmap / that you would accept a PR for?

**Comment by kovetskiy** [comment]
Hey, I haven't even heard about Confluence blog posts before. Would be glad to review a PR if you are willing to contribute. :cat:

**Comment by mrdavidlaing** [comment]
Sounds good - will try get to it later this week

**Comment by mrdavidlaing** [comment]
Closing in favour of linked PR
