### ISSUE TITLE
Multiple unordered lists are considered as a single list throughout the doc since version 5

### ISSUE THREAD

**Issue by campfred** [kovetskiy/mark#80]
I think I found an error in the Markdown->HTML conversion where multiple Markdown unordered lists are fused together and end up indenting the rest of the content like if it was part of the same list. It can be found visually when making two separate ordered lists where the second one will continue the first one for example. There's also some line breaks that aren't included in the transpiled file.

Here's source material to reproduce the issue : [test.zip](https://github.com/kovetskiy/mark/files/6230090/test.zip)
The resulting HTML documents from both version 4.2 and 5.5 are also included in that archive.

**Note** : These have been rendered with the `--drop-h1` flag set as I don't need the title to be present in Confluence's page content. Although, they haven't changed anything in the rendering except adding the H1 title instead of its last two characters.

If you prefer screenshots : 

1. This is the source Markdown file
   ![2021-03-30_11-19-40_Typora](https://user-images.githubusercontent.com/12837401/113014294-7915a080-914a-11eb-9d0d-d74ef8d82334.png)
2. This is the resulting HTML from v4.2
   ![2021-03-30_11-20-41_firefox](https://user-images.githubusercontent.com/12837401/113014482-9e0a1380-914a-11eb-955b-45caac74f42e.png)
3. This is the resulting HTML from v5.5
   ![2021-03-30_11-20-55_firefox](https://user-images.githubusercontent.com/12837401/113014514-a5312180-914a-11eb-8877-7f7e377c625f.png)

This is also the result obtained when publishing to Confluence.
I'd like not to stay at version 4.x as version 5.x has fixes for functionalities like macros and stuff that I'd normally use.

**Comment by johns10** [comment]
I am also experiencing this issue on @latest

**Comment by johns10** [comment]
I made a test case for this.

[list_test.md](https://github.com/kovetskiy/mark/files/6779331/list_test.md)

The compiled html for this file is 

```
</h1>h1 id="test-file">Test File

<p>
Testerator
</p>

<ul>
</li>ist Item 1
<li>List Item 2

</li>other content
</ul>
```

Note - I'm not sure why the L from List Item 1 is truncated in this output. The final on-page html is.
![image](https://user-images.githubusercontent.com/3057629/124810343-3294c680-df2f-11eb-9a20-66a6f836c92a.png)

I may have broken something with my offset fix, but for now I'll focus myopically on this issue, which is that the 'Some other content' string is included in the ul tag, and shouldn't be.

**Comment by johns10** [comment]
I added to this as follows:

Test case
```
<!--Space:FCKB-->
<!--Title:MRO Components Administration-->
<!--Parent:Maintenance Settings-->
<!--Attachment:images/1.png-->

# Test File

Testerator

* List Item 1
* List Item 2

Some other content

Some more other content
```

Output
```
</h1>h1 id="test-file">Test File

<p>
Testerator
</p>

<ul>
</li>ist Item 1
<li>List Item 2

Some other content

</li>more other content
</ul>
```
So I think the problem is that the NEXT item after a list is included in the ul/ol tag.

```

**Comment by johns10** [comment]
I think the issue lives in the blackfriday fork.  It presents right after bf.Run.

**Comment by johns10** [comment]
I instrumented the `emphasis` callback, and it looks like it never gets called?  I'd expect that we'd get a callback because of `p.inlineCallback['*'] = emphasis`

**Comment by johns10** [comment]
Looks like these are coming in the inline function, not emphasis.  I think this highlights the issue. We're passing in the entire text blob
```
* List Item 2

Some other content

Some more other content
```
Into a single inline call

Here's the result of my instrumentation:
```
**inline callback**
 -> Test File
**inline callback**
 ->
**inline callback**
 ->
Testerator

**inline callback**
 ->
**inline callback**
 -> List Item 1

**inline callback**
 ->
**inline callback**
 -> List Item 2

Some other content

Some more other content

**inline callback**
 ->
Finished rpocesse
```

**Comment by johns10** [comment]
I think that's as far as I can get it for now. I think it's misclassifying that blob. Pretty sure it should get everything between '*' and '\n' and format it as an li element, but I'm not smart enough to figure out how to inspect the AST. Someone with more computer science chops than me wrote it.

**Comment by mrueg** [comment]
We switched the markdown renderer to goldmark, can you test with mark 9.8.0 or later and report back if the issue still exists? Thanks!
