### ISSUE TITLE
Ignore md files which don't include required metadata

### ISSUE THREAD

**Issue by rslotte** [kovetskiy/mark#87]
Is there a way to skip markdown files which don't include the required metadata rather than exiting with a fatal error?

My use case is that I have a big collection of markdown files where I would like to push only the files that include the metadata to Confluence. I'm using a glob pattern to run Mark so that I don't have to list each file separately.

**Comment by kovetskiy** [comment]
Hi, you can do this using grep:

```
grep -R -l 'Space:' *.md | xargs -n1 -I{} mark ... -f {}
```

**Comment by rslotte** [comment]
Thanks for the good work 👍 Have solved it like you suggested
