### ISSUE TITLE
Handle semantic line breaks when converting markdown file to an HTML file

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [kovetskiy/mark#92]
Thanks for the work on `mark,` this is an amazing tool! It works great for my needs except for one subtle detail.
I believe it's the "opposite" of another issue: https://github.com/kovetskiy/mark/issues/61

Having this markdown snippet which follows the [semantic line breaks](https://sembr.org/) guide:

```markdown
If you want to save the file,
you can click Save.
```

Will generate this HTML file (which I see by using the `--dry-run` flag):

```html
<p>If you want to save the file,
you can click Save.</p>
```

When this HTML gets rendered in Confluence, the line breaks within the `<p>` tag are respected resulting in awkward breaks:

![image](https://user-images.githubusercontent.com/59651540/125070575-110f1880-e0b0-11eb-82f6-eaf4b48a2b61.png)

I believe most Markdown renderers would ignore single line breaks, so wrapping the text around some length shouldn't affect the rendered outcome. However, I assume Confluence handles the text within the `<p>` tag in a particular way treating those "soft" line breaks as break lines. 

Do you have any control over the HTML generation in the `mark` code to be able to handle it differently to not let Jira make those line breaks?

Many thanks.

**Comment by kovetskiy** [comment]
Hi,
> Do you have any control over the HTML generation in the mark code to be able to handle it differently to not let Jira make those line breaks?
Yes we do have control over the HTML generation and we even have tests that assert that your 1st snippet converts to your 2nd snippet. The problem is that Confluence doesn't care about the fact that newlines in <p> should not be treated as a newline by any RFC.

Do you have any particular ideas on how we can solve this?

**Comment by alexey-tereshenkov-oxb** [comment]
Hi Egor, thanks for looking into this. I've explored a little bit about Confluence handling HTML input and couldn't come up with any bright idea how to work around this.

We have a choice to either let the clients of mark to write and run a pre-processor on their Markdown files to replace single line breaks with an empty space:

```
This is one paragraph
that spans multiple lines
and is sweet and short.

This is a new paragraph
that starts on a next line
and again spanning multiple lines.
```

so that the string above would be converted using something like this (Python snippet): 

```
print(re.sub(r'(?<!\n)\n(?!\n)', ' ', s))
```

to 

```
This is one paragraph that spans multiple lines and is sweet and short.

This is a new paragraph that starts on a next line and again spanning multiple lines.
```

or have this logic embedded in `mark`, potentially with a flag `--keep-semantic-line-breaks` or something similar.

I believe it would be useful to let users to choose whether they would want to munge the markdown files first (in memory) to remove semantic line breaks or they do want to treat the line breaks literally as they see the file in the text editor (so we should keep two ways to handle the semantic line breaks).

Does this make any sense?

Cheers.

**Comment by nyarly** [comment]
I've just run into this issue. IMO `mark` should collapse newlines in a `<p>` automatically. Confluence's behavior is _weird_, and I don't think there's an argument for accepting it. If anything, perhaps there should be a flag for `--allow-nonconforming-linebreaks` or something to disable reflowing of paragraphs.

**Comment by GusAntoniassi** [comment]
Hello, I've opened #186 to solve this issue by removing newlines within `<p>` tags with RegExp. Suggestions and contributions are more than welcome!

**Comment by Skeeve** [comment]
FYI: I cannot reproduce the issue using the most recent mark and Confluence 7.15.0 I get the expected result.

Source and generated HTML are as described in the ticket, but Confluence does not render any linebreaks. Looking at the source the browser holds, the linebreak is not present.

**Comment by nyarly** [comment]
```
Confluence Cloud
Confluence 1000.0.0-f2458dd01458
```
definitely still exhibits this behavior
