### ISSUE TITLE
Migration: Import existed confluence spaces to md

### ISSUE THREAD

**Issue by malys** [kovetskiy/mark#97]
Hi,

I have many confluence spaces created manually. I want to test "mark" (great idea for developers).
I would like to convert existed spaces to md to initialize my repository and after that, use it as code base to modify my documentation.
Is it possible?

**Comment by kovetskiy** [comment]
Hi, no, it's not possible with Mark. May be it is possible with some other
tools that can parse confluence and convert html to markdown. But mark can
only convert from MD to html.

**Comment by jagguli** [comment]
I was looking for the same since the description for the project says 'sync' but its only push
I suppose one would need to use the confluence to fetch the doc and  convert it to MD

**Comment by malys** [comment]
Thanks
